# Cas de test : (module, fonctionnalité, objectif, préconditions, étapes, données, attendu, priorité, appareil)
T = 'Téléphone + Ordinateur'
LEO = [
# --- Accès
("Accès et compte","Page de connexion","Se connecter à Léo","Compte de test existant","1. Ouvrir /legion\n2. Saisir e-mail et mot de passe\n3. Valider","Compte de test fourni par Beau","On arrive sur « Mes entreprises ». Le fond de ville animé s'affiche sans ralentir la page.","Haute",T),
("Accès et compte","Continuer avec Finjaro","Entrer dans Léo avec un compte Finjaro déjà connecté","Être connecté sur finjaro.net","1. Aller sur la place de marché, connecté\n2. Ouvrir Léo\n3. Cliquer « Continuer avec Finjaro »","—","Connexion sans ressaisir le mot de passe, même compte.","Haute",T),
("Accès et compte","Connexion depuis Finjaro Accounting","Passer d'Accounting à Léo sans se reconnecter","Être connecté sur Accounting","1. Dans Accounting, ouvrir le lien vers Léo\n2. Observer l'arrivée","—","On arrive connecté dans Léo, sur le même compte. Un lien réutilisé une 2e fois est refusé.","Moyenne","Ordinateur"),
("Accès et compte","Déconnexion","Se déconnecter proprement","Être connecté","1. Ouvrir le menu du compte\n2. Se déconnecter\n3. Revenir sur /legion","—","Retour à la page de connexion ; aucune donnée de l'entreprise visible.","Haute",T),
("Accès et compte","Langue FR / EN","Changer la langue de l'interface","Être connecté","1. Basculer FR → EN\n2. Parcourir 3 écrans\n3. Revenir en FR","—","Tous les libellés changent ; aucun texte resté dans l'autre langue.","Moyenne",T),
("Accès et compte","Thème sombre / clair","Changer la palette","Être connecté","1. Passer en clair\n2. Parcourir salon, tâches, fiche agent\n3. Repasser en sombre","—","Textes lisibles partout, aucun bloc blanc sur blanc ou noir sur noir.","Basse",T),
# --- Fonder
("Fonder une entreprise","Fonder à partir d'un modèle","Créer une entreprise depuis un modèle prêt","Être connecté","1. « Fonder une entreprise »\n2. Choisir un modèle (ex. cabinet d'avocats)\n3. Répondre à « Qui es-tu ? » et « Ce que tu veux obtenir »\n4. Valider","Nom : Test Cabinet","L'entreprise est créée avec ses services et ses agents ; on arrive dans les salons.","Haute",T),
("Fonder une entreprise","Fonder sans modèle","Créer une entreprise vide et choisir ses rôles","Être connecté","1. Fonder sans modèle\n2. Cliquer sur des rôles proposés\n3. Valider","Nom : Test Libre","Seuls les rôles cliqués deviennent des agents.","Haute",T),
("Fonder une entreprise","Agent d'aide à la fondation","Se faire guider pendant la fondation","Écran Fonder ouvert","1. Poser une question à l'agent d'aide\n2. Suivre sa suggestion","« Je vends des pagnes en ligne »","Réponse en français, pertinente pour le métier, en moins de 15 s.","Moyenne",T),
("Fonder une entreprise","Catalogue de métiers","Ajouter un agent depuis le catalogue","Entreprise créée","1. Agents → « + Agent »\n2. Chercher un métier\n3. L'ajouter","Recherche : « comptable »","Le métier est trouvé ; l'agent apparaît dans l'équipe avec photo et poste.","Haute",T),
("Fonder une entreprise","Mes entreprises / tour de contrôle","Voir et ouvrir ses entreprises","2 entreprises créées","1. Ouvrir « Mes entreprises »\n2. Ouvrir l'une puis l'autre","—","Les deux s'affichent avec leurs chiffres ; on entre dans la bonne.","Moyenne",T),
# --- Salons
("Salons et messages","Écrire dans un salon","Envoyer un message et recevoir une réponse d'agent","Entreprise avec agents allumés","1. Ouvrir le salon Direction\n2. Écrire une question simple","« Bonjour, où en est-on ? »","Un agent répond en français, en quelques secondes ; « X écrit… » s'affiche pendant l'attente.","Haute",T),
("Salons et messages","Mentionner un agent","Obtenir la réponse d'un agent précis","Salon ouvert","1. Écrire @ + nom d'un agent\n2. Poser la question","« @Kwame combien a-t-on vendu ? »","C'est l'agent mentionné qui répond.","Haute",T),
("Salons et messages","Types de message","Envoyer une Question, une Proposition, un À trancher, une Tâche","Salon ouvert","1. Choisir chaque type sous la zone de saisie\n2. Envoyer un message avec chacun","—","Chaque message porte son étiquette ; « Tâche » crée une carte dans le tableau des tâches.","Moyenne",T),
("Salons et messages","Message vocal","Envoyer un vocal compris par les agents","Micro autorisé","1. Maintenir le micro\n2. Parler 5 s\n3. Envoyer","Phrase dite à voix haute","Le vocal est transcrit ; l'agent répond au contenu (pas seulement « 🎤 »).","Haute","Téléphone"),
("Salons et messages","Fichier Excel / CSV / PDF","Faire lire un document aux agents","Un fichier .xlsx ou .pdf","1. Joindre le fichier dans un salon\n2. Demander un résumé","Petit tableau de ventes","L'agent cite des éléments réels du fichier.","Haute","Ordinateur"),
("Salons et messages","Photo","Envoyer une photo","Appareil photo ou galerie","1. Joindre une photo\n2. Demander ce qu'on voit","—","La photo s'affiche ; l'agent la décrit.","Moyenne","Téléphone"),
("Salons et messages","Commandes /","Utiliser les commandes rapides","Salon ouvert","1. Taper « / »\n2. Choisir une commande","—","La liste des commandes s'ouvre et la commande choisie s'exécute.","Basse","Ordinateur"),
("Salons et messages","Réponse rapide","Mesurer la vitesse sur une question simple","Salon ouvert","1. Écrire « bonne nuit »\n2. Chronométrer","—","Réponse en moins de 10 s.","Moyenne",T),
("Salons et messages","Questions des agents à l'humain","Répondre à une question posée par un agent","Un agent a posé une question","1. Ouvrir la question\n2. Répondre","—","La réponse est prise en compte ; la question passe en « réglée ».","Moyenne",T),
# --- Agents
("Agents","Fiche agent","Consulter la fiche d'un agent","Entreprise avec agents","1. Cliquer sur un agent\n2. Lire la fiche","—","On voit : ce qu'on attend de lui, sa personnalité, ses limites, son autonomie, ses droits, sa mémoire.","Haute",T),
("Agents","Modifier un agent","Changer la personnalité ou le poste","Fiche ouverte","1. « Modifier »\n2. Changer la personnalité\n3. Enregistrer\n4. Lui écrire","—","La modification est gardée et se ressent dans ses réponses.","Moyenne",T),
("Agents","Autonomie","Régler jusqu'où l'agent agit seul","Fiche ouverte","1. Passer de Supervisé à Semi-autonome\n2. Lui donner une tâche","—","Le réglage est gardé ; en Supervisé il propose, en Semi-autonome il agit sur ce qui ne coûte rien.","Haute",T),
("Agents","Droits","Passer un agent de Lecture seule à Peut modifier","Fiche ouverte","1. Changer les droits\n2. Vérifier dans l'atelier","—","En lecture seule il ne modifie rien ; en Peut modifier il peut écrire du code.","Haute","Ordinateur"),
("Agents","Interrupteur","Éteindre et rallumer un agent","Agent allumé","1. Éteindre l'agent\n2. Lui écrire\n3. Le rallumer","—","Éteint, il ne répond pas ; rallumé, il répond.","Haute",T),
("Agents","Interrupteur par service","Éteindre tout un service","Plusieurs agents dans un service","1. Éteindre le service Marketing\n2. Écrire dans son salon","—","Aucun agent du service ne répond.","Moyenne",T),
("Agents","Engager via Confirmer","Valider l'arrivée d'un agent proposé","Une proposition d'agent en attente","1. Ouvrir la proposition\n2. Cliquer « Confirmer »","—","L'agent rejoint l'équipe ; rien ne se fait sans le clic.","Haute",T),
("Agents","Galerie","Parcourir les agents en galerie","Entreprise avec agents","1. Ouvrir « Galerie »","—","Photos, noms et postes s'affichent sans image cassée.","Basse",T),
("Agents","Mémoire de l'agent","Vérifier qu'il se souvient","Avoir déjà échangé avec l'agent","1. Lui rappeler une consigne donnée plus tôt\n2. Lui demander de l'appliquer","—","Il retrouve la consigne dans sa mémoire.","Moyenne",T),
("Agents","Contester un livrable","Renvoyer un travail insuffisant","Un livrable rendu","1. Ouvrir le livrable\n2. « Contester » avec un motif","« Trop long, fais court »","L'agent refait le travail en tenant compte du motif.","Moyenne",T),
("Agents","Encourager","Féliciter un agent","Un livrable rendu","1. « Encourager »","—","Le geste est enregistré (badge / historique).","Basse",T),
("Agents","Renforcer un service","Ajouter du monde à un service débordé","Un service avec beaucoup de tâches","1. « Renforcer »\n2. Choisir le service","—","Un ou plusieurs agents rejoignent le service.","Moyenne",T),
("Agents","Intérim / expert à la mission","Faire venir un agent temporaire","Entreprise créée","1. Demander un intérim ou un expert\n2. Lui confier une mission","—","L'agent arrive, fait la mission, puis repart ou reste selon le choix.","Moyenne",T),
("Agents","Export / import d'agents","Sauvegarder puis réimporter une équipe","Entreprise avec agents","1. Exporter l'équipe\n2. Importer dans une autre entreprise de test","—","Les agents réimportés ont le même poste et la même personnalité.","Basse","Ordinateur"),
# --- Tâches
("Tâches et missions","Tableau des tâches","Voir les tâches par statut","Entreprise active","1. Ouvrir le tableau des tâches\n2. Filtrer par service","—","Colonnes À faire / En cours / Revue / Fait ; le filtre fonctionne.","Haute",T),
("Tâches et missions","Créer une tâche","Donner une tâche à un agent","Tableau ouvert","1. « Nouvelle tâche »\n2. Titre, agent, priorité\n3. Enregistrer","« Préparer le visuel de la promo »","La carte apparaît dans À faire, attribuée au bon agent.","Haute",T),
("Tâches et missions","Commenter une tâche","Échanger sur une tâche","Une tâche existante","1. Ouvrir la tâche\n2. Ajouter un commentaire","—","Le commentaire s'affiche avec l'heure ; l'agent peut répondre.","Moyenne",T),
("Tâches et missions","Déplacer une tâche","Faire avancer une tâche","Une tâche À faire","1. La passer En cours puis Fait","—","Le statut change et reste après rechargement.","Moyenne",T),
("Tâches et missions","Bibliothèque de missions","Lancer une mission récurrente","Entreprise créée","1. Ouvrir la bibliothèque\n2. Choisir une mission hebdomadaire\n3. L'activer","—","La mission crée ses tâches à la bonne fréquence.","Moyenne",T),
# --- Réunions
("Réunions","Lancer une réunion","Réunir 2 à 5 agents sur un sujet","Au moins 2 agents","1. « Réunion »\n2. Sujet + agents\n3. « Ouvrir la réunion »","« Comment trouver nos 20 premiers clients ? »","Chaque agent prend position, ils se répondent, puis une conclusion et une décision à trancher.","Haute",T),
("Réunions","Types de réunion","Tester vote, avocat du diable, négociation, investisseurs, crise, et si, rétro, budget","Au moins 3 agents","1. Lancer chaque type une fois","—","Le déroulé correspond au type (ex. vote = décompte des voix).","Moyenne","Ordinateur"),
("Réunions","Écouter la réunion","Entendre la réunion à plusieurs voix","Une réunion terminée","1. « Écouter »","—","Chaque agent a sa voix ; le son est clair.","Moyenne",T),
("Réunions","Trancher","Prendre la décision demandée par les agents","Réunion terminée avec « À toi de trancher »","1. Répondre à la décision","—","La décision est enregistrée et reprise dans le rapport du soir.","Haute",T),
# --- Voix
("Voix et appels","Appeler un agent","Parler à un agent de vive voix","Micro autorisé","1. « Appeler » sur la fiche d'un agent\n2. Parler\n3. Raccrocher","—","L'agent répond à voix haute, en français, sur le sujet.","Haute",T),
("Voix et appels","Jarvis (commande vocale)","Piloter Léo à la voix","Micro autorisé","1. Ouvrir Jarvis\n2. Dire « ouvre le tableau des tâches »","—","L'écran demandé s'ouvre.","Moyenne","Ordinateur"),
# --- Rapports
("Rapports et tableau de bord","Rapport du soir","Recevoir le point du jour","Entreprise active dans la journée","1. Attendre le rapport (ou le déclencher en test)\n2. Le lire","—","Sections Fait aujourd'hui / Une décision t'attend / Demain ; contenu fidèle à la journée.","Haute",T),
("Rapports et tableau de bord","Écouter le rapport","Entendre le rapport du soir","Un rapport reçu","1. « Écouter »","—","Lecture audio claire et complète.","Moyenne",T),
("Rapports et tableau de bord","Alertes","Être prévenu d'un problème","Provoquer une alerte (ex. budget à 80 %)","1. Consommer le budget d'un agent\n2. Observer","—","Une alerte s'affiche à 80 %.","Moyenne",T),
("Rapports et tableau de bord","Tableau de bord","Voir KPI, coût, charge et santé par agent","Entreprise active","1. Ouvrir le tableau de bord","—","Chiffres cohérents avec l'activité réelle ; aucun chiffre inventé.","Haute","Ordinateur"),
("Rapports et tableau de bord","Rapport de transparence du mois","Consulter le bilan mensuel","Entreprise de plus d'un mois (ou données de test)","1. Ouvrir le rapport du mois","—","Le bilan s'affiche et reprend les vrais chiffres.","Basse","Ordinateur"),
("Rapports et tableau de bord","Journal des choix","Vérifier la trace des décisions","Des décisions prises","1. Ouvrir le journal","—","Chaque décision est datée et signée ; impossible de la modifier.","Moyenne","Ordinateur"),
# --- Vues
("Vues et outils","Organigramme","Voir l'équipe par service","Entreprise avec agents","1. L'immeuble → Organigramme\n2. Exporter en PNG, SVG et PDF","—","Photos, postes, chef → équipe ; les 3 exports s'ouvrent correctement.","Moyenne","Ordinateur"),
("Vues et outils","Frise","Voir l'activité dans le temps","Entreprise active","1. Ouvrir la frise\n2. Changer de période","—","Les événements s'affichent dans l'ordre.","Basse",T),
("Vues et outils","Présentation (diapositives)","Générer une présentation","Entreprise active","1. Ouvrir « Présentation »","—","Les diapositives se génèrent et défilent.","Basse","Ordinateur"),
("Vues et outils","Tableau d'idées","Déposer et trier des idées","Entreprise créée","1. Ajouter une idée\n2. La déplacer","—","L'idée est gardée après rechargement.","Basse",T),
("Vues et outils","Documents de l'entreprise","Donner des documents de référence aux agents","Un document texte ou PDF","1. Ajouter le document\n2. Poser une question dessus","—","L'agent répond en s'appuyant sur le document.","Haute","Ordinateur"),
("Vues et outils","Wiki des agents","Consulter le wiki","Entreprise active","1. Ouvrir le wiki","—","Les pages s'affichent et sont à jour.","Basse",T),
("Vues et outils","Membres et rôles","Inviter un collègue humain","Deux comptes de test","1. Inviter le 2e compte\n2. Lui donner un rôle\n3. Se connecter avec lui","—","Il voit l'entreprise avec les droits de son rôle, pas plus.","Haute",T),
# --- Atelier
("Atelier de code","Ouvrir l'atelier","Accéder à l'atelier de code","Entreprise créée","1. Ouvrir l'atelier","—","Éditeur, fichiers, aperçu et terminal s'affichent.","Haute","Ordinateur"),
("Atelier de code","L'agent code en direct","Demander un petit site à un agent","Atelier ouvert","1. Demander « une page d'accueil pour ma boutique »\n2. Regarder l'éditeur","—","Le code s'écrit en direct dans l'éditeur ; l'aperçu montre la page.","Haute","Ordinateur"),
("Atelier de code","Palette Ctrl+K","Utiliser la palette de commandes","Atelier ouvert","1. Ctrl+K\n2. Lancer une commande","—","La palette s'ouvre et la commande s'exécute.","Basse","Ordinateur"),
("Atelier de code","Envoyer sur GitHub","Pousser le code sur une branche après accord","GitHub connecté (compte de test)","1. « Envoyer sur GitHub »\n2. Confirmer","—","Le code part sur une branche leo/… , jamais sur la branche principale.","Haute","Ordinateur"),
# --- Connecteurs
("Connecteurs","Se connecter avec GitHub","Brancher son compte GitHub","Compte GitHub de test","1. Connecteurs → GitHub\n2. Autoriser","—","Le compte est branché ; les dépôts apparaissent.","Haute","Ordinateur"),
("Connecteurs","Linear / Jira","Brancher un outil de tickets","Compte de test Linear ou Jira","1. Brancher\n2. Créer une réunion depuis un ticket","—","Le ticket est lu ; la réunion reprend son contenu.","Moyenne","Ordinateur"),
("Connecteurs","Veille RSS","Suivre un flux d'actualités","URL d'un flux RSS","1. Ajouter le flux\n2. Attendre la veille","—","Les agents résument les nouveautés du flux.","Basse","Ordinateur"),
("Connecteurs","Finjaro Accounting","Brancher la comptabilité","Compte Accounting de test","1. « Se connecter avec Finjaro Accounting »\n2. Demander un chiffre","—","L'agent lit les vrais chiffres (comptes de test exclus des totaux).","Moyenne","Ordinateur"),
("Connecteurs","Supabase / Cloudflare / Vercel","Brancher en lecture seule","Compte de test du service","1. Brancher\n2. Demander un état","—","Lecture seule : l'agent lit, ne modifie rien.","Basse","Ordinateur"),
("Connecteurs","Claude / ChatGPT (MCP)","Piloter Léo depuis un autre assistant","Assistant compatible MCP","1. Ajouter le serveur Léo\n2. Demander la liste des tâches","—","L'assistant lit les tâches de l'entreprise.","Basse","Ordinateur"),
("Connecteurs","Mon ordinateur","Confier une tâche sur l'ordinateur","Extension de navigateur installée","1. Créer une tâche « mon ordinateur »\n2. Suivre l'exécution","—","La tâche s'exécute et rend compte ; rien sans accord.","Basse","Ordinateur"),
# --- Monde 3D
("Monde 3D","Entrer dans la ville","Ouvrir le monde 3D","Entreprise créée","1. Ouvrir la ville","—","La ville se charge, fluide (pas de saccade forte).","Moyenne",T),
("Monde 3D","Immeuble et réception","Se déplacer jusqu'à la réception","Monde ouvert","1. Marcher jusqu'à l'immeuble\n2. Parler à la réceptionniste","—","La réceptionniste répond ; l'ascenseur mène aux étages.","Moyenne",T),
("Monde 3D","Salle de réunion / atelier 3D","Voir les agents travailler","Monde ouvert","1. Aller en salle de réunion puis à l'atelier","—","Les agents sont à leur poste et bougent.","Basse",T),
("Monde 3D","Ciel réel","Vérifier l'heure et la météo","Monde ouvert","1. Comparer le ciel à l'heure locale","—","Jour/nuit et météo correspondent au pays de l'utilisateur.","Basse",T),
# --- Offre
("Offre et contact","Premium et crédit offert","Voir l'offre Premium et le crédit de 2 €","Compte neuf","1. Ouvrir « Premium »\n2. Vérifier le crédit","—","Le crédit offert s'affiche ; le prix est dans la monnaie de l'utilisateur.","Moyenne",T),
("Offre et contact","Nous contacter","Envoyer un message à l'équipe","Être connecté","1. « Nous contacter »\n2. Envoyer un message","« Test du formulaire »","Confirmation d'envoi ; l'équipe reçoit l'e-mail.","Moyenne",T),
("Offre et contact","Hors ligne","Utiliser Léo sans réseau","Mode avion","1. Couper le réseau\n2. Naviguer","—","Un message clair signale l'absence de réseau ; rien ne plante.","Basse","Téléphone"),
]
MKT = [
("Accueil et recherche","Accueil","Découvrir les articles","—","1. Ouvrir finjaro.net (ou staging)","—","Accueil rapide, articles avec photo, prix et boutique.","Haute",T),
("Accueil et recherche","Recherche","Trouver un article","—","1. Chercher un mot","« robe »","Résultats pertinents ; « aucun résultat » si rien.","Haute",T),
("Accueil et recherche","Catégories","Parcourir une catégorie","—","1. Ouvrir une catégorie","—","Seuls les articles de la catégorie s'affichent.","Moyenne",T),
("Accueil et recherche","Prix dans la monnaie du visiteur","Voir les prix dans sa monnaie","Tester depuis 2 pays (ou réglage du pays)","1. Régler le pays sur Royaume-Uni\n2. Puis Canada\n3. Puis Cameroun","—","£ au Royaume-Uni, $ CA au Canada, FCFA au Cameroun ; jamais FCFA par défaut pour un pays inconnu.","Haute",T),
("Accueil et recherche","Langue FR / EN","Changer la langue","—","1. Basculer la langue","—","Tous les textes changent ; aucun texte ne réduit Finjaro à un seul pays.","Moyenne",T),
("Fiche article","Fiche article","Voir un article en détail","—","1. Ouvrir un article","—","Photos, prix, description, boutique, bouton panier.","Haute",T),
("Fiche article","Prix sur demande","Commander un article sans prix affiché","Un article « prix sur demande »","1. L'ajouter au panier","—","L'ajout est possible et le prix est demandé à la vendeuse.","Haute",T),
("Fiche article","Contacter la vendeuse","Écrire ou appeler depuis la fiche","—","1. WhatsApp\n2. Appel\n3. Message dans l'appli","—","Chaque bouton ouvre le bon canal.","Haute","Téléphone"),
("Fiche article","Fiche traduite","Lire une fiche dans l'autre langue","Article saisi en français","1. Passer en anglais","—","La description est traduite.","Basse",T),
("Panier et commande","Panier sans compte","Remplir un panier sans être connecté","Déconnecté","1. Ajouter 2 articles\n2. Ouvrir le panier","—","Le panier garde les articles ; la connexion n'est demandée qu'à la commande.","Haute",T),
("Panier et commande","Passer commande","Commander avec paiement à la livraison","Compte de test acheteur","1. Valider le panier\n2. Adresse + téléphone\n3. Confirmer","Adresse de test","Commande créée (statut new) ; la vendeuse est prévenue.","Haute",T),
("Panier et commande","Suivi de commande","Suivre sa commande","Une commande passée","1. Ouvrir « Mes commandes »","—","Statut à jour ; historique lisible.","Haute",T),
("Panier et commande","Relance vendeuse / escalade","Vérifier les relances automatiques","Commande non confirmée (données de test)","1. Laisser la commande en new\n2. Vérifier la relance puis l'escalade à 72 h","—","La vendeuse est relancée ; à 72 h l'acheteuse est orientée vers d'autres boutiques.","Moyenne","Ordinateur"),
("Panier et commande","Achat groupé","Acheter à plusieurs","Article éligible","1. Lancer un achat groupé\n2. Inviter un 2e compte","—","Le groupe se forme ; le prix groupé s'applique.","Basse",T),
("Panier et commande","Preuve de livraison","Confirmer la réception","Commande livrée (test)","1. Confirmer la livraison avec preuve","—","La preuve est enregistrée ; statut livré.","Moyenne","Téléphone"),
("Compte","Inscription","Créer un compte","E-mail de test","1. S'inscrire\n2. Ouvrir le lien de confirmation","—","Le lien mène sur finjaro.net et valide le compte.","Haute",T),
("Compte","Connexion / mot de passe oublié","Se connecter et réinitialiser","Compte de test","1. Se connecter\n2. Tester « mot de passe oublié »","—","Connexion OK ; l'e-mail de réinitialisation arrive.","Haute",T),
("Compte","Suivre une boutique","S'abonner à une boutique","Connecté","1. « Suivre » sur une boutique","—","La boutique apparaît dans les suivies.","Basse",T),
("Compte","Partager","Partager une boutique ou une vidéo","—","1. « Partager »","—","Le lien s'ouvre sur la bonne page.","Basse","Téléphone"),
("Espace vendeuse","Créer sa boutique","Ouvrir une boutique","Compte de test vendeuse","1. « Ouvrir ma boutique »\n2. Nom, pays, photo\n3. Valider","Boutique Test","La boutique est créée ; la devise suit le pays de la boutique.","Haute",T),
("Espace vendeuse","Ajouter un article","Publier un article","Boutique créée","1. « Ajouter »\n2. Photo, titre, prix\n3. Publier","Prix dans la devise de la boutique","L'article est en ligne ; le prix saisi est gardé à l'identique.","Haute",T),
("Espace vendeuse","Photo → fiche","Remplir la fiche à partir d'une photo","Boutique créée","1. Prendre une photo\n2. Laisser remplir la fiche","—","Titre et description proposés ; modifiables avant publication.","Moyenne","Téléphone"),
("Espace vendeuse","Prix conseillé","Recevoir une suggestion de prix","Article en cours de saisie","1. Demander un prix conseillé","—","Une fourchette est proposée, sans chiffre inventé.","Basse",T),
("Espace vendeuse","Carte « Articles sans prix »","Repérer ses articles sans prix","Au moins un article sans prix","1. Ouvrir l'espace vendeuse","—","La carte liste les articles sans prix.","Moyenne",T),
("Espace vendeuse","Confirmer une commande","Accepter une commande reçue","Une commande new","1. Ouvrir la commande\n2. Confirmer","—","Statut confirmé ; l'acheteuse est prévenue.","Haute",T),
("Espace vendeuse","Prix côté vendeuse","Vérifier la devise des écrans vendeuse","Boutique dans un pays donné","1. Comparer les prix affichés","—","Tous les écrans vendeuse sont dans la devise de SA boutique, pas celle du téléphone.","Haute",T),
("Espace vendeuse","Mon argent","Voir ses ventes et encaissements","Des ventes de test","1. Ouvrir « Mon argent »","—","Chiffres exacts ; comptes de test exclus.","Haute",T),
("Espace vendeuse","Carnet de crédit","Noter une vente à crédit","Boutique créée","1. Ajouter une dette client\n2. La marquer payée","—","Le solde se met à jour.","Moyenne",T),
("Espace vendeuse","Vente en direct","Lancer une vente en direct","Boutique créée","1. Démarrer un direct","—","Le direct démarre ; les acheteuses peuvent commander.","Basse","Téléphone"),
("Messagerie","Messagerie acheteuse ↔ vendeuse","Échanger dans l'appli","Deux comptes de test","1. Écrire à une boutique\n2. Répondre côté vendeuse","—","Messages reçus des deux côtés, dans l'ordre, avec notification.","Haute",T),
("Messagerie","Assistante Finia","Poser une question à l'assistante","—","1. Ouvrir Finia\n2. Poser une question","« Comment je commande ? »","Réponse juste, en français, sans promesse impossible.","Moyenne",T),
("Services","Page Services","Trouver un artisan ou un prestataire","—","1. Ouvrir /services\n2. Filtrer par métier","—","Les fiches s'affichent ; contact possible.","Moyenne",T),
("Services","Prendre rendez-vous","Réserver un créneau","Un prestataire avec agenda","1. Choisir un créneau\n2. Confirmer","—","Le rendez-vous est enregistré des deux côtés.","Moyenne",T),
("Général","Téléphone (390 px) et grand écran","Vérifier l'affichage sur les deux formats","—","1. Parcourir accueil, fiche, panier, espace vendeuse sur téléphone\n2. Puis sur grand écran","—","Rien de coupé (visages, boutons, textes) ; pas de défilement horizontal.","Haute",T),
("Général","Applications Android / iOS","Vérifier l'appli installée","Appli installée","1. Ouvrir l'appli\n2. Refaire le parcours commande","—","Même comportement que sur finjaro.net.","Haute","Téléphone"),
]
