import { chromium } from 'playwright';
import { createServer } from 'http';
import { readFileSync, existsSync } from 'fs';
import { join, extname } from 'path';
const DIST='/home/user/henribeaubayemi/dist';
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg'};
const srv=createServer((req,res)=>{let p=join(DIST,req.url.split('?')[0]);if(!existsSync(p)||extname(p)==='')p=join(DIST,'index.html');
  res.writeHead(200,{'content-type':MIME[extname(p)]||'application/octet-stream'});res.end(readFileSync(p));});
await new Promise(r=>srv.listen(4708,r));
const now=Date.now(),U='aaaa1111-1111-4111-8111-111111111111',SHOP='ssss1111-1111-4111-8111-111111111111';
const session={access_token:'f',token_type:'bearer',expires_in:3600,expires_at:Math.floor(now/1000)+3600,refresh_token:'f',user:{id:U,aud:'authenticated',role:'authenticated',phone:'237651234567',app_metadata:{},user_metadata:{name:'Aïcha K.'},created_at:new Date(now).toISOString()}};
const profile={id:U,name:'Aïcha K.',country:'CM',currency:'FCFA',is_vendor:true};
const shopRow={id:SHOP,owner_id:U,slug:'chez-aicha',name:'Chez Aïcha',country:'CM',city:'Douala',categories:['mode_femme'],status:'active'};
const prod={id:'p1',shop_id:SHOP,name:'Robe wax',price_fcfa:15000,images:['/demo-products/wd-03.jpg'],stock:3,is_active:true,created_at:new Date(now).toISOString()};
const browser=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const ctx=await browser.newContext({viewport:{width:390,height:797},deviceScaleFactor:2,locale:'fr-FR'});
await ctx.addInitScript(([k,s])=>localStorage.setItem(k,JSON.stringify(s)),['sb-bokwivwizghdlaedczbw-auth-token',session]);
const page=await ctx.newPage();
await page.route('**/realtime/v1/**',r=>r.abort());
await page.route('**/auth/v1/**',r=>r.fulfill({json:session}));
await page.route('**/rest/v1/**',route=>{const url=new URL(route.request().url());
  const table=url.pathname.split('/rest/v1/')[1].split('?')[0];
  const single=(route.request().headers()['accept']||'').includes('vnd.pgrst.object');
  let rows=[];if(table==='shops')rows=[shopRow];else if(table==='profiles')rows=[profile];else if(table==='products')rows=[prod];
  const h={'content-type':'application/json','content-range':`0-${Math.max(rows.length-1,0)}/${rows.length}`};
  return route.fulfill({status:200,headers:h,body:JSON.stringify(single?rows[0]??null:rows)});});
await page.goto('http://localhost:4708/vendor/products',{waitUntil:'domcontentloaded'});
await page.waitForTimeout(2500);
const b=page.locator('a[href="/vendor/products/bulk"]');
console.log('Bouton « En masse » présent :', await b.count());
console.log('Position :', JSON.stringify(await b.boundingBox()));
console.log('Visible :', await b.isVisible());
await page.screenshot({path:'check-bulkbtn.png'});
await browser.close();srv.close();
