import { chromium } from 'playwright';
import { createServer } from 'http';
import { readFileSync, existsSync, readdirSync } from 'fs';
import { join, extname } from 'path';
const DIST='/home/user/henribeaubayemi/dist';
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg'};
const srv=createServer((req,res)=>{let p=join(DIST,req.url.split('?')[0]);if(!existsSync(p)||extname(p)==='')p=join(DIST,'index.html');
  res.writeHead(200,{'content-type':MIME[extname(p)]||'application/octet-stream'});res.end(readFileSync(p));});
await new Promise(r=>srv.listen(4710,r));
const now=Date.now(),U='aaaa1111-1111-4111-8111-111111111111',SHOP='ssss1111-1111-4111-8111-111111111111';
const session={access_token:'f',token_type:'bearer',expires_in:3600,expires_at:Math.floor(now/1000)+3600,refresh_token:'f',user:{id:U,aud:'authenticated',role:'authenticated',phone:'237651234567',app_metadata:{},user_metadata:{name:'A'},created_at:new Date(now).toISOString()}};
const profile={id:U,name:'A',country:'CM',currency:'FCFA',is_vendor:true};
const shopRow={id:SHOP,owner_id:U,slug:'s',name:'Boutique Tante',country:'CM',city:'Douala',categories:['mode_femme'],status:'active'};
const browser=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const ctx=await browser.newContext({viewport:{width:390,height:797},deviceScaleFactor:2,locale:'fr-FR'});
await ctx.addInitScript(([k,s])=>localStorage.setItem(k,JSON.stringify(s)),['sb-bokwivwizghdlaedczbw-auth-token',session]);
const page=await ctx.newPage();
page.on('pageerror',e=>console.log('PAGEERROR',String(e).slice(0,160)));
await page.route('**/realtime/v1/**',r=>r.abort());
await page.route('**/auth/v1/**',r=>r.fulfill({json:session}));
await page.route('**/storage/v1/**',r=>r.fulfill({status:200,headers:{'content-type':'application/json'},body:JSON.stringify({Key:'ok',path:'ok'})}));
await page.route('**/rest/v1/**',route=>{const url=new URL(route.request().url());
  const table=url.pathname.split('/rest/v1/')[1].split('?')[0];
  const single=(route.request().headers()['accept']||'').includes('vnd.pgrst.object');
  let rows=[];if(table==='shops')rows=[shopRow];else if(table==='profiles')rows=[profile];
  const h={'content-type':'application/json','content-range':`0-${Math.max(rows.length-1,0)}/${rows.length}`};
  return route.fulfill({status:200,headers:h,body:JSON.stringify(single?rows[0]??null:rows)});});
await page.goto('http://localhost:4710/vendor/products/bulk',{waitUntil:'domcontentloaded'});
await page.waitForTimeout(2500);
const photos=readdirSync(join(DIST,'demo-products')).filter(f=>f.endsWith('.jpg')).slice(0,4).map(f=>join(DIST,'demo-products',f));
await page.locator('input[type=file]').first().setInputFiles(photos);
await page.waitForTimeout(6000);
const rowSel=()=>page.locator('.space-y-2 select');
console.log('Rayon visible sur chaque ligne :', await rowSel().count());
console.log('Avant  :', await rowSel().evaluateAll(e=>e.map(x=>x.value)));
// Changer le rayon commun + prix, puis appliquer
await page.locator('section select').first().selectOption('enfants_bebe');
await page.locator('section input[type=number]').first().fill('4500');
await page.locator('button',{hasText:'Appliquer à tous les articles'}).click();
await page.waitForTimeout(1200);
console.log('Après  :', await rowSel().evaluateAll(e=>e.map(x=>x.value)));
console.log('Prix   :', await page.locator('.space-y-2 input[type=number]').evaluateAll(e=>e.map(x=>x.value)));
const toast=await page.locator('text=/appliqué/i').first().textContent().catch(()=>null);
console.log('Message:', toast?.trim());
await page.screenshot({path:'test-apply.png'});
await browser.close();srv.close();
