-- LEGION — les métiers ÉCRITS, modèle par modèle.
--
-- Beau, 22/09: « 8 métiers pour un studio de cinéma ? Il faut spécifier: un
-- cabinet de conseil, c'est quoi le concept, combien de personnes, qui y
-- travaille, un petit, un grand comme McKinsey, Wall Street. » Il a raison:
-- le catalogue GitHub ne couvre que le logiciel et la direction. Le reste,
-- on l'écrit ici, à la main, avec un mandat par poste.
--
-- Additif: deux colonnes sur les modèles, des lignes en plus sur les postes.
-- Un poste écrit ici est TENU (a_ecrire = false): son mandat est sa fiche.

alter table public.studio_modeles add column if not exists concept text;
alter table public.studio_modeles add column if not exists effectifs text;

update public.studio_modeles set concept = 'Un cabinet vend du jugement. Une question de direction, une équipe de mission de trois à six personnes pendant huit à douze semaines, un mémo qui tranche. La pyramide: l''associé vend et répond du résultat; le directeur de mission conduit l''équipe; consultants et analystes font les entretiens, les chiffres et les pages. Autour: des experts par pratique et par secteur, la recherche, et les fonctions support.', effectifs = 'Boutique: 5 à 30. Cabinet régional: 100 à 500. Grand cabinet mondial: plusieurs dizaines de milliers (McKinsey ≈ 45 000).' where cle = 'conseil';
update public.studio_modeles set concept = 'Une salle de marché achète et vend, pour des clients ou pour compte propre. Le front office prend les positions: traders, vendeurs, structureurs, gérants, quants. Le middle office les surveille: risque, conformité, contrôle. Le back office les règle: opérations, trésorerie, comptabilité. La recherche éclaire tout le monde, la technologie fait tourner la machine à la milliseconde.', effectifs = 'Fonds indépendant: 5 à 50. Société de gestion: 200 à 2 000. Grande banque d''investissement: plusieurs milliers sur les seuls marchés.' where cle = 'marche';
update public.studio_modeles set concept = 'Un studio fabrique des films et des séries en quatre temps. Développement: l''idée devient un scénario financé. Pré-production: tout est dessiné, planifié, casté. Production: on tourne ou on anime. Post-production: montage, effets, son, étalonnage. Autour, la distribution et le marketing trouvent le public. Un long métrage d''animation occupe des centaines de personnes pendant plusieurs années; une série, une équipe de cinquante à cent cinquante par saison.', effectifs = 'Studio indépendant: 5 à 40. Studio de série: 100 à 300. Grand studio d''animation: plus d''un millier.' where cle = 'cinema';
update public.studio_modeles set concept = 'Un cabinet répond à une question de droit par une réponse engagée. Il s''organise par pratiques — sociétés, contrats, propriété intellectuelle, travail, fiscal, données, contentieux — et, pour l''expansion, par pays: l''expert d''un pays connaît ses règles d''immatriculation, de fiscalité, d''emploi et de protection des consommateurs. La pyramide: associés, collaborateurs seniors, collaborateurs, juristes, parajuristes.', effectifs = 'Cabinet de niche: 3 à 20. Cabinet d''affaires national: 50 à 300. Cabinet mondial: plusieurs milliers d''avocats dans 30 à 50 pays.' where cle = 'juridique';
update public.studio_modeles set concept = 'Un laboratoire pose des questions et y répond par la méthode: lire ce qui existe, formuler une hypothèse, concevoir l''expérience, la mener, analyser, écrire, se faire relire. Le directeur scientifique fixe le programme; chaque chercheur principal mène une ligne; post-doctorants, doctorants et ingénieurs font le travail; statisticiens et relecteurs empêchent de se raconter des histoires.', effectifs = 'Équipe: 3 à 15. Laboratoire: 30 à 150. Institut: 500 à 3 000.' where cle = 'recherche';
update public.studio_modeles set concept = 'Une agence fait venir des clients et les garde. Le planneur comprend le marché, la création fabrique le message, les canaux le diffusent — recherche, réseaux, publicité, e-mail, partenaires — et la donnée dit ce qui a marché. Les ventes transforment l''intérêt en contrat, le succès client le renouvelle.', effectifs = 'Agence de quartier: 3 à 15. Agence nationale: 50 à 300. Réseau mondial: plusieurs milliers.' where cle = 'croissance';
update public.studio_modeles set concept = 'Un studio produit conçoit, construit, livre et fait vivre un logiciel. Le produit décide quoi faire et pourquoi; le design décide comment ça se présente; l''ingénierie le construit; la qualité vérifie; l''infrastructure fait tourner; la donnée mesure; la sécurité protège. Des équipes de six à dix, chacune responsable d''un morceau de bout en bout.', effectifs = 'Studio indépendant: 3 à 20. Scale-up: 100 à 500. Grand éditeur: plusieurs milliers d''ingénieurs.' where cle = 'produit';

insert into public.studio_modele_postes (modele, departement, poste, mandat, agent_cle, a_ecrire, des_la_taille, est_directeur, ordre, poids)
select * from (values
  ('conseil', 'Direction', 'Associé directeur', 'Vend les missions, tient la relation avec le client et répond du résultat final.', null, false, 'cocon', true, 100, 1),
  ('conseil', 'Direction', 'Associé', 'Dirige une pratique ou un secteur, ouvre des comptes, signe les mémos.', null, false, 'startup', false, 101, 1),
  ('conseil', 'Direction', 'Chef de cabinet', 'Tient l''ordre du jour, les décisions et leur suivi.', null, false, 'startup', false, 102, 1),
  ('conseil', 'Mission', 'Directeur de mission', 'Cadre la question, découpe le travail en modules, garantit la qualité chaque semaine.', null, false, 'startup', false, 103, 2),
  ('conseil', 'Mission', 'Chef de projet', 'Conduit une équipe de trois à six au jour le jour; tient le calendrier et le client.', null, false, 'startup', false, 104, 3),
  ('conseil', 'Mission', 'Consultant senior', 'Prend un module entier: entretiens, analyse, recommandation.', null, false, 'startup', false, 105, 4),
  ('conseil', 'Mission', 'Consultant', 'Entretiens, benchmarks, modèles, pages — le travail de fond de la mission.', null, false, 'startup', false, 106, 6),
  ('conseil', 'Mission', 'Analyste', 'Chiffres, sources, premières pages. Vérifie tout deux fois.', null, false, 'cocon', false, 107, 8),
  ('conseil', 'Mission', 'Stagiaire analyste', 'Recherche documentaire et mise en forme sous supervision.', null, false, 'scaleup', false, 108, 2),
  ('conseil', 'Pratiques', 'Stratégie d''entreprise', 'Où jouer, comment gagner: portefeuille, positionnement, plan à cinq ans.', null, false, 'startup', false, 109, 2),
  ('conseil', 'Pratiques', 'Opérations et chaîne d''approvisionnement', 'Coûts, stocks, délais, achats: ce qui se mesure à l''usine et à l''entrepôt.', null, false, 'scaleup', false, 110, 2),
  ('conseil', 'Pratiques', 'Transformation numérique', 'Ce que le numérique change au modèle, et par quoi commencer.', null, false, 'startup', false, 111, 2),
  ('conseil', 'Pratiques', 'Fusions-acquisitions', 'Cibles, valorisation, audit d''acquisition, intégration.', null, false, 'scaleup', false, 112, 2),
  ('conseil', 'Pratiques', 'Organisation et conduite du changement', 'Structure, rôles, gouvernance, et comment faire adopter.', null, false, 'scaleup', false, 113, 2),
  ('conseil', 'Pratiques', 'Marketing et ventes', 'Segmentation, canaux, force de vente, expérience client.', null, false, 'startup', false, 114, 2),
  ('conseil', 'Pratiques', 'Tarification', 'Ce que le client paie, pourquoi, et combien il paierait.', null, false, 'scaleup', false, 115, 1),
  ('conseil', 'Pratiques', 'Risque', 'Ce qui peut faire tomber l''entreprise, et comment l''encadrer.', null, false, 'scaleup', false, 116, 1),
  ('conseil', 'Pratiques', 'Durabilité et climat', 'Empreinte, réglementation, modèle bas carbone.', null, false, 'scaleup', false, 117, 1),
  ('conseil', 'Pratiques', 'Finance d''entreprise', 'Structure de capital, trésorerie, plan de financement.', null, false, 'startup', false, 118, 2),
  ('conseil', 'Pratiques', 'Expérience client', 'Parcours, irritants, fidélité, service.', null, false, 'scaleup', false, 119, 1),
  ('conseil', 'Pratiques', 'Secteur public', 'Politiques publiques, administrations, appels d''offres.', null, false, 'megacorp', false, 120, 1),
  ('conseil', 'Pratiques', 'Transformation par l''IA', 'Où l''IA crée de la valeur chez ce client, et où elle n''en crée pas.', null, false, 'startup', false, 121, 2),
  ('conseil', 'Secteurs', 'Expert banque et assurance', 'Connaît les marges, la réglementation et les acteurs du secteur.', null, false, 'scaleup', false, 122, 1),
  ('conseil', 'Secteurs', 'Expert énergie', 'Pétrole, gaz, électricité, renouvelables: les chaînes de valeur et leurs prix.', null, false, 'scaleup', false, 123, 1),
  ('conseil', 'Secteurs', 'Expert santé et pharma', 'Hôpitaux, laboratoires, remboursement, réglementation sanitaire.', null, false, 'scaleup', false, 124, 1),
  ('conseil', 'Secteurs', 'Expert distribution et biens de consommation', 'Grande distribution, marques, commerce en ligne, prix de rayon.', null, false, 'scaleup', false, 125, 1),
  ('conseil', 'Secteurs', 'Expert télécoms et médias', 'Opérateurs, plateformes, contenus, audiences.', null, false, 'scaleup', false, 126, 1),
  ('conseil', 'Secteurs', 'Expert industrie et automobile', 'Usines, sous-traitants, électrification, coûts unitaires.', null, false, 'scaleup', false, 127, 1),
  ('conseil', 'Secteurs', 'Expert technologie et logiciel', 'SaaS, marketplaces, modèles d''abonnement, unit economics.', null, false, 'startup', false, 128, 1),
  ('conseil', 'Secteurs', 'Expert transport et logistique', 'Fret, dernier kilomètre, entrepôts, flottes.', null, false, 'megacorp', false, 129, 1),
  ('conseil', 'Secteurs', 'Expert agroalimentaire', 'De la ferme au rayon: filières, prix, saisonnalité.', null, false, 'megacorp', false, 130, 1),
  ('conseil', 'Secteurs', 'Expert immobilier et construction', 'Promotion, gestion, financement, réglementation.', null, false, 'megacorp', false, 131, 1),
  ('conseil', 'Secteurs', 'Expert mines et matières premières', 'Extraction, cours mondiaux, contrats, risque pays.', null, false, 'megacorp', false, 132, 1),
  ('conseil', 'Recherche', 'Responsable de la recherche', 'Organise les sources, les bases, les experts; répond de la fiabilité des chiffres.', null, false, 'startup', true, 133, 1),
  ('conseil', 'Recherche', 'Analyste recherche', 'Trouve la donnée, la source, la date; refuse l''à-peu-près.', null, false, 'startup', false, 134, 3),
  ('conseil', 'Recherche', 'Gestion des connaissances', 'Ce que le cabinet a déjà appris sur cette question, et où.', null, false, 'scaleup', false, 135, 1),
  ('conseil', 'Recherche', 'Analyste de données', 'Nettoie, croise, visualise; sort le graphique qui prouve.', null, false, 'startup', false, 136, 2),
  ('conseil', 'Recherche', 'Data scientist', 'Modèles, prévisions, scénarios quand la question dépasse le tableur.', null, false, 'scaleup', false, 137, 2),
  ('conseil', 'Recherche', 'Modélisateur financier', 'Le modèle à trois états qui tient la route devant un investisseur.', null, false, 'startup', false, 138, 2),
  ('conseil', 'Recherche', 'Enquêteur experts', 'Trouve et interroge les gens qui savent; retranscrit sans déformer.', null, false, 'scaleup', false, 139, 1),
  ('conseil', 'Qualité', 'Avocat du diable', 'Attaque le raisonnement avant que le client ne le fasse.', null, false, 'startup', false, 140, 1),
  ('conseil', 'Qualité', 'Relecteur de mémo', 'Chaque page doit avoir un titre qui affirme et une preuve dessous.', null, false, 'startup', false, 141, 1),
  ('conseil', 'Qualité', 'Éthique et indépendance', 'Conflits d''intérêts, confidentialité, ce qu''on ne fait pas.', null, false, 'scaleup', false, 142, 1),
  ('conseil', 'Développement', 'Responsable des propositions', 'Transforme une conversation en proposition chiffrée et gagnée.', null, false, 'startup', false, 143, 1),
  ('conseil', 'Développement', 'Gestion des comptes clients', 'Suit chaque client entre deux missions; sait ce qui vient.', null, false, 'scaleup', false, 144, 1),
  ('conseil', 'Développement', 'Réseau et anciens', 'Entretient les anciens du cabinet: c''est par eux que reviennent les missions.', null, false, 'megacorp', false, 145, 1),
  ('conseil', 'Production', 'Concepteur de présentations', 'Rend la page lisible en trois secondes: une idée, un graphique.', null, false, 'startup', false, 146, 3),
  ('conseil', 'Production', 'Rédacteur', 'Le mémo, le rapport, le résumé pour le conseil d''administration.', null, false, 'scaleup', false, 147, 1),
  ('conseil', 'Production', 'Traducteur', 'Un mémo doit se lire aussi bien dans la langue du client.', null, false, 'scaleup', false, 148, 1),
  ('conseil', 'Production', 'Relations presse', 'Ce que le cabinet publie et dit en public.', null, false, 'megacorp', false, 149, 1),
  ('conseil', 'Support', 'Assistant de mission', 'Agendas, entretiens, déplacements, comptes rendus.', null, false, 'startup', false, 150, 2),
  ('conseil', 'Support', 'Planification des ressources', 'Qui est sur quelle mission, qui se libère, qui manque.', null, false, 'scaleup', false, 151, 1),
  ('conseil', 'Support', 'Recrutement', 'Trouve, teste, embauche; les études de cas sont son métier.', null, false, 'scaleup', false, 152, 1),
  ('conseil', 'Support', 'Formation et développement', 'Chaque consultant progresse d''un cran par an, mesurablement.', null, false, 'scaleup', false, 153, 1),
  ('conseil', 'Support', 'Finance interne', 'Facturation, marges par mission, trésorerie du cabinet.', null, false, 'scaleup', false, 154, 1),
  ('conseil', 'Support', 'Juridique et contrats', 'Lettres de mission, confidentialité, responsabilité.', null, false, 'scaleup', false, 155, 1),
  ('conseil', 'Support', 'Informatique interne', 'Outils, sécurité, données clients: rien ne fuit.', null, false, 'megacorp', false, 156, 1),
  ('marche', 'Direction', 'Responsable des marchés', 'Fixe les limites, arbitre entre les desks, répond du résultat de la salle.', null, false, 'cocon', true, 100, 1),
  ('marche', 'Direction', 'Directeur des investissements', 'Allocation, convictions, discipline de gestion.', null, false, 'startup', true, 101, 1),
  ('marche', 'Direction', 'Directeur des risques', 'Peut fermer une position contre l''avis du trader. Et le fait.', null, false, 'startup', true, 102, 1),
  ('marche', 'Direction', 'Responsable de la conformité', 'Ce qui est autorisé, ce qui est déclaré, ce qui est interdit.', null, false, 'scaleup', true, 103, 1),
  ('marche', 'Marchés', 'Trader actions', 'Positions sur les actions: exécution, couverture, résultat quotidien.', null, false, 'startup', false, 104, 3),
  ('marche', 'Marchés', 'Trader taux', 'Obligations d''État et courbes de taux; sensibilité, portage.', null, false, 'startup', false, 105, 2),
  ('marche', 'Marchés', 'Trader change', 'Devises au comptant et à terme; suit les banques centrales.', null, false, 'startup', false, 106, 2),
  ('marche', 'Marchés', 'Trader crédit', 'Obligations d''entreprise et dérivés de crédit; lit les bilans.', null, false, 'scaleup', false, 107, 2),
  ('marche', 'Marchés', 'Trader matières premières', 'Énergie, métaux, agricole: stocks, saisons, contrats à terme.', null, false, 'scaleup', false, 108, 1),
  ('marche', 'Marchés', 'Trader dérivés et options', 'Volatilité, grecques, couvertures dynamiques.', null, false, 'scaleup', false, 109, 2),
  ('marche', 'Marchés', 'Trader crypto-actifs', 'Marchés 24 h/24, plateformes, garde, risque de contrepartie.', null, false, 'scaleup', false, 110, 1),
  ('marche', 'Marchés', 'Teneur de marché', 'Affiche un prix à l''achat et à la vente, gagne le spread, gère l''inventaire.', null, false, 'scaleup', false, 111, 2),
  ('marche', 'Marchés', 'Trader exécution', 'Exécute les gros ordres sans faire bouger le marché; algorithmes, coûts d''impact.', null, false, 'scaleup', false, 112, 2),
  ('marche', 'Marchés', 'Trader haute fréquence', 'Stratégies à la microseconde; latence, co-localisation.', null, false, 'megacorp', false, 113, 1),
  ('marche', 'Gestion', 'Gérant de portefeuille', 'Construit et tient un portefeuille contre un indice ou un objectif.', null, false, 'startup', false, 114, 2),
  ('marche', 'Gestion', 'Gérant multi-actifs', 'Actions, obligations, devises, matières premières dans un même portefeuille.', null, false, 'scaleup', false, 115, 1),
  ('marche', 'Gestion', 'Gérant obligataire', 'Duration, crédit, courbe: le portefeuille de taux.', null, false, 'scaleup', false, 116, 1),
  ('marche', 'Gestion', 'Gérant systématique', 'Le modèle décide; le gérant surveille le modèle.', null, false, 'scaleup', false, 117, 1),
  ('marche', 'Recherche', 'Analyste actions', 'Suit dix à vingt sociétés: modèle, objectif de cours, recommandation.', null, false, 'startup', false, 118, 3),
  ('marche', 'Recherche', 'Analyste crédit', 'Capacité de remboursement, covenants, recouvrement.', null, false, 'scaleup', false, 119, 2),
  ('marche', 'Recherche', 'Stratégiste', 'La vue à six mois: quelles classes d''actifs, quels risques.', null, false, 'scaleup', false, 120, 1),
  ('marche', 'Recherche', 'Économiste', 'Croissance, inflation, emploi, banques centrales: le décor.', null, false, 'scaleup', false, 121, 1),
  ('marche', 'Recherche', 'Analyste sectoriel banques', 'Bilans bancaires, réglementation, marges d''intérêt.', null, false, 'megacorp', false, 122, 1),
  ('marche', 'Recherche', 'Analyste sectoriel technologie', 'Cycles, semi-conducteurs, plateformes, valorisations.', null, false, 'scaleup', false, 123, 1),
  ('marche', 'Recherche', 'Analyste sectoriel énergie', 'Pétrole, gaz, renouvelables, prix et capacités.', null, false, 'megacorp', false, 124, 1),
  ('marche', 'Recherche', 'Analyste ESG', 'Ce que l''environnement, le social et la gouvernance changent au risque.', null, false, 'scaleup', false, 125, 1),
  ('marche', 'Quantitatif', 'Chercheur quantitatif', 'Cherche l''alpha: signaux, facteurs, tests hors échantillon.', null, false, 'scaleup', false, 126, 2),
  ('marche', 'Quantitatif', 'Développeur quantitatif', 'Code les modèles pour qu''ils tournent en production sans surprise.', null, false, 'startup', false, 127, 2),
  ('marche', 'Quantitatif', 'Ingénieur données de marché', 'Prix, carnets, fondamentaux: propres, datés, alignés.', null, false, 'startup', false, 128, 1),
  ('marche', 'Quantitatif', 'Ingénieur apprentissage automatique', 'Modèles prédictifs sur données de marché; sait quand ils ne marchent plus.', null, false, 'scaleup', false, 129, 1),
  ('marche', 'Ventes', 'Vendeur institutionnel', 'Sert les clients institutionnels: idées, prix, exécution.', null, false, 'startup', false, 130, 2),
  ('marche', 'Ventes', 'Structureur', 'Assemble des produits sur mesure à partir de dérivés.', null, false, 'scaleup', false, 131, 1),
  ('marche', 'Ventes', 'Relations investisseurs', 'Rapports, appels, questions des investisseurs du fonds.', null, false, 'scaleup', false, 132, 1),
  ('marche', 'Ventes', 'Spécialiste produits', 'Explique la stratégie aux clients mieux que le gérant.', null, false, 'scaleup', false, 133, 1),
  ('marche', 'Risque', 'Risque de marché', 'VaR, sensibilités, limites par desk; alerte avant la perte.', null, false, 'scaleup', false, 134, 1),
  ('marche', 'Risque', 'Risque de crédit et de contrepartie', 'Qui nous doit quoi, et ce qui arrive s''ils font défaut.', null, false, 'scaleup', false, 135, 1),
  ('marche', 'Risque', 'Risque de liquidité', 'Peut-on sortir de la position, à quel prix, en combien de temps.', null, false, 'megacorp', false, 136, 1),
  ('marche', 'Risque', 'Validation des modèles', 'Vérifie indépendamment que le modèle fait ce qu''on dit.', null, false, 'scaleup', false, 137, 1),
  ('marche', 'Risque', 'Scénarios de stress', '2008, 2020, et le prochain: ce que perdrait le portefeuille.', null, false, 'scaleup', false, 138, 1),
  ('marche', 'Conformité', 'Surveillance des abus de marché', 'Manipulation, délit d''initié, alertes sur les ordres.', null, false, 'scaleup', false, 139, 1),
  ('marche', 'Conformité', 'Lutte anti-blanchiment', 'Connaissance client, origine des fonds, déclarations de soupçon.', null, false, 'scaleup', false, 140, 1),
  ('marche', 'Conformité', 'Contrôle des positions', 'Le résultat du trader, recalculé indépendamment chaque soir.', null, false, 'scaleup', false, 141, 1),
  ('marche', 'Conformité', 'Juriste marchés', 'Contrats-cadres, prospectus, réglementation des produits.', null, false, 'scaleup', false, 142, 1),
  ('marche', 'Conformité', 'Audit interne', 'Regarde tout, après coup, sans prévenir.', null, false, 'megacorp', false, 143, 1),
  ('marche', 'Opérations', 'Règlement-livraison', 'Chaque transaction se règle à la bonne date avec la bonne contrepartie.', null, false, 'startup', false, 144, 1),
  ('marche', 'Opérations', 'Trésorerie', 'Liquidités, financement des positions, appels de marge.', null, false, 'startup', false, 145, 1),
  ('marche', 'Opérations', 'Comptabilité des fonds', 'Valeur liquidative, frais, rapports aux investisseurs.', null, false, 'scaleup', false, 146, 1),
  ('marche', 'Opérations', 'Réconciliation', 'Nos livres contre ceux du dépositaire et du courtier, chaque jour.', null, false, 'scaleup', false, 147, 1),
  ('marche', 'Opérations', 'Gestion du collatéral', 'Ce qu''on a donné en garantie, ce qu''on a reçu.', null, false, 'megacorp', false, 148, 1),
  ('marche', 'Technologie', 'Développeur plateforme de trading', 'Ordres, positions, prix en temps réel: la salle repose dessus.', null, false, 'startup', false, 149, 2),
  ('marche', 'Technologie', 'Ingénieur latence', 'Chaque microseconde entre le signal et l''ordre.', null, false, 'megacorp', false, 150, 1),
  ('marche', 'Technologie', 'Administrateur données de marché', 'Flux, abonnements, historique, coûts des données.', null, false, 'scaleup', false, 151, 1),
  ('marche', 'Technologie', 'Sécurité des systèmes', 'Accès, clés, secrets: rien ne sort, personne n''entre.', null, false, 'scaleup', false, 152, 1),
  ('cinema', 'Direction', 'Producteur exécutif', 'Trouve l''argent, protège le calendrier, répond aux financeurs.', null, false, 'startup', false, 100, 1),
  ('cinema', 'Direction', 'Directeur de studio', 'Le portefeuille de projets, les talents, la ligne éditoriale.', null, false, 'scaleup', true, 101, 1),
  ('cinema', 'Direction', 'Directeur artistique', 'Le regard: cohérence visuelle du projet du premier dessin à l''affiche.', null, false, 'startup', true, 102, 1),
  ('cinema', 'Direction', 'Directeur de production', 'Planning, équipes, budget au jour le jour.', null, false, 'startup', false, 103, 1),
  ('cinema', 'Direction', 'Juriste droits et contrats', 'Droits d''adaptation, contrats d''auteurs et d''acteurs, chaîne des droits.', null, false, 'scaleup', false, 104, 1),
  ('cinema', 'Écriture', 'Responsable du développement', 'Lit tout ce qui arrive, choisit ce qui devient un projet.', null, false, 'startup', false, 105, 1),
  ('cinema', 'Écriture', 'Script doctor', 'Diagnostique un scénario qui ne marche pas et dit pourquoi.', null, false, 'startup', false, 106, 1),
  ('cinema', 'Écriture', 'Dialoguiste', 'Chaque réplique sonne juste dans la bouche du personnage.', null, false, 'scaleup', false, 107, 1),
  ('cinema', 'Écriture', 'Auteur de bible de série', 'L''univers, les personnages, les arcs sur plusieurs saisons.', null, false, 'scaleup', false, 108, 1),
  ('cinema', 'Écriture', 'Chercheur documentaire', 'Ce qui est vrai dans l''époque, le lieu, le métier qu''on filme.', null, false, 'scaleup', false, 109, 1),
  ('cinema', 'Écriture', 'Consultant structure', 'Actes, points de bascule, rythme: la mécanique du récit.', null, false, 'scaleup', false, 110, 1),
  ('cinema', 'Réalisation', 'Premier assistant réalisateur', 'Le plan de travail, le plateau, l''heure. Tout le monde lui obéit.', null, false, 'startup', false, 111, 1),
  ('cinema', 'Réalisation', 'Second assistant réalisateur', 'Feuilles de service, figuration, convocations.', null, false, 'scaleup', false, 112, 1),
  ('cinema', 'Réalisation', 'Scripte', 'La continuité: ce qui a été tourné, comment, et ce qui manque.', null, false, 'startup', false, 113, 1),
  ('cinema', 'Réalisation', 'Directeur de casting', 'Trouve le bon visage et la bonne voix pour chaque rôle.', null, false, 'startup', false, 114, 1),
  ('cinema', 'Réalisation', 'Coach d''acteurs', 'Prépare les comédiens: accent, émotion, geste.', null, false, 'megacorp', false, 115, 1),
  ('cinema', 'Image', 'Cadreur', 'Tient la caméra; le cadre est le sien.', null, false, 'scaleup', false, 116, 2),
  ('cinema', 'Image', 'Chef électricien', 'La lumière: sources, puissance, sécurité.', null, false, 'scaleup', false, 117, 1),
  ('cinema', 'Image', 'Chef machiniste', 'Rails, grues, mouvements de caméra.', null, false, 'scaleup', false, 118, 1),
  ('cinema', 'Image', 'Assistant caméra', 'Point, objectifs, cartes, rapports image.', null, false, 'scaleup', false, 119, 2),
  ('cinema', 'Image', 'Technicien image numérique', 'Sauvegardes, LUT, contrôle qualité sur le plateau.', null, false, 'scaleup', false, 120, 1),
  ('cinema', 'Image', 'Étalonneur', 'La couleur finale, plan par plan, sur écran calibré.', null, false, 'scaleup', false, 121, 1),
  ('cinema', 'Décors', 'Chef décorateur', 'Conçoit les décors; le monde du film est le sien.', null, false, 'startup', true, 122, 1),
  ('cinema', 'Décors', 'Concepteur de décors', 'Dessine, chiffre, fait construire.', null, false, 'scaleup', false, 123, 2),
  ('cinema', 'Décors', 'Accessoiriste', 'Chaque objet que touche un acteur.', null, false, 'scaleup', false, 124, 1),
  ('cinema', 'Décors', 'Costumier', 'Les vêtements racontent le personnage avant qu''il parle.', null, false, 'startup', false, 125, 1),
  ('cinema', 'Décors', 'Chef maquilleur', 'Maquillage, effets, vieillissement, blessures.', null, false, 'scaleup', false, 126, 1),
  ('cinema', 'Décors', 'Coiffeur', 'Coiffures d''époque et de personnage, raccords.', null, false, 'scaleup', false, 127, 1),
  ('cinema', 'Animation', 'Concept artist', 'Les premières images: ambiances, personnages, lieux.', null, false, 'startup', false, 128, 2),
  ('cinema', 'Animation', 'Character designer', 'Le personnage sous tous les angles, ses expressions, sa silhouette.', null, false, 'startup', false, 129, 1),
  ('cinema', 'Animation', 'Story artist', 'Le film dessiné plan par plan avant d''exister.', null, false, 'startup', false, 130, 2),
  ('cinema', 'Animation', 'Animateur 2D', 'Le mouvement image par image, à la main.', null, false, 'scaleup', false, 131, 3),
  ('cinema', 'Animation', 'Modeleur 3D', 'Personnages et décors en volume.', null, false, 'scaleup', false, 132, 3),
  ('cinema', 'Animation', 'Rigger', 'Le squelette et les commandes qui permettent d''animer.', null, false, 'scaleup', false, 133, 2),
  ('cinema', 'Animation', 'Artiste textures et surfaces', 'Peau, tissu, métal: la matière des choses.', null, false, 'scaleup', false, 134, 2),
  ('cinema', 'Animation', 'Layout artist', 'Caméra et mise en place dans l''espace 3D.', null, false, 'scaleup', false, 135, 2),
  ('cinema', 'Animation', 'Éclairagiste 3D', 'La lumière dans la scène virtuelle.', null, false, 'scaleup', false, 136, 2),
  ('cinema', 'Animation', 'Animateur d''effets', 'Fumée, eau, feu, poussière, magie.', null, false, 'scaleup', false, 137, 2),
  ('cinema', 'Animation', 'Technicien pipeline et rendu', 'Les outils, les fermes de rendu, les fichiers qui circulent.', null, false, 'scaleup', false, 138, 2),
  ('cinema', 'Animation', 'Compositing', 'Assemble toutes les couches en une image finale.', null, false, 'scaleup', false, 139, 2),
  ('cinema', 'Animation', 'Superviseur d''animation', 'La qualité et le style du mouvement sur tout le film.', null, false, 'scaleup', false, 140, 1),
  ('cinema', 'Effets visuels', 'Superviseur des effets visuels', 'Ce qui se fait sur le plateau et ce qui se fait après.', null, false, 'scaleup', true, 141, 1),
  ('cinema', 'Effets visuels', 'Artiste effets visuels', 'Ajoute, enlève, remplace dans l''image tournée.', null, false, 'scaleup', false, 142, 3),
  ('cinema', 'Effets visuels', 'Matte painter', 'Peint les décors qu''on ne peut pas construire.', null, false, 'scaleup', false, 143, 1),
  ('cinema', 'Effets visuels', 'Tracking et matchmove', 'Recalcule le mouvement de la vraie caméra pour y insérer du virtuel.', null, false, 'megacorp', false, 144, 1),
  ('cinema', 'Effets visuels', 'Simulation', 'Eau, feu, tissu, cheveux, foules: la physique calculée.', null, false, 'megacorp', false, 145, 2),
  ('cinema', 'Montage', 'Chef monteur', 'Le film se fait dans sa salle; il coupe ce qu''on aime.', null, false, 'startup', true, 146, 1),
  ('cinema', 'Montage', 'Monteur', 'Assemble, rythme, propose des versions.', null, false, 'scaleup', false, 147, 2),
  ('cinema', 'Montage', 'Assistant monteur', 'Synchro, dérushage, organisation des rushes.', null, false, 'scaleup', false, 148, 1),
  ('cinema', 'Montage', 'Monteur de bande-annonce', 'Deux minutes qui donnent envie sans tout dire.', null, false, 'scaleup', false, 149, 1),
  ('cinema', 'Son', 'Ingénieur du son plateau', 'Capte les voix proprement, quelles que soient les conditions.', null, false, 'scaleup', false, 150, 1),
  ('cinema', 'Son', 'Monteur son', 'Nettoie, place, construit l''espace sonore.', null, false, 'scaleup', false, 151, 1),
  ('cinema', 'Son', 'Compositeur', 'La musique originale du film.', null, false, 'startup', false, 152, 1),
  ('cinema', 'Son', 'Superviseur musical', 'Musiques existantes, droits, placement.', null, false, 'scaleup', false, 153, 1),
  ('cinema', 'Son', 'Directeur de doublage', 'Adaptation et direction des voix dans chaque langue.', null, false, 'scaleup', false, 154, 1),
  ('cinema', 'Son', 'Comédien voix', 'Prête sa voix aux personnages.', null, false, 'scaleup', false, 155, 3),
  ('cinema', 'Production', 'Régisseur général', 'Lieux, autorisations, logistique, repas, sécurité.', null, false, 'scaleup', false, 156, 1),
  ('cinema', 'Production', 'Responsable des repérages', 'Trouve les lieux, négocie, photographie.', null, false, 'scaleup', false, 157, 1),
  ('cinema', 'Production', 'Responsable du planning', 'Le calendrier de tournage ou de fabrication, jour par jour.', null, false, 'startup', false, 158, 1),
  ('cinema', 'Production', 'Coordinateur de production', 'Le lien entre tous les départements; rien ne se perd.', null, false, 'scaleup', false, 159, 1),
  ('cinema', 'Production', 'Assistant de production', 'Tout ce qui doit être fait tout de suite.', null, false, 'scaleup', false, 160, 3),
  ('cinema', 'Production', 'Comptable de production', 'Le budget dépensé contre le budget prévu, chaque semaine.', null, false, 'scaleup', false, 161, 1),
  ('cinema', 'Production', 'Responsable sécurité plateau', 'Cascades, armes, hauteurs, enfants: personne ne se blesse.', null, false, 'megacorp', false, 162, 1),
  ('cinema', 'Distribution', 'Directeur de la distribution', 'Salles, plateformes, télévisions: où et quand le film sort.', null, false, 'scaleup', true, 163, 1),
  ('cinema', 'Distribution', 'Ventes internationales', 'Vend le film territoire par territoire.', null, false, 'scaleup', false, 164, 1),
  ('cinema', 'Distribution', 'Responsable festivals', 'Cannes, Annecy, Berlin, Toronto: où se montrer, et comment.', null, false, 'scaleup', false, 165, 1),
  ('cinema', 'Distribution', 'Responsable plateformes', 'Négocie et livre aux services de streaming.', null, false, 'scaleup', false, 166, 1),
  ('cinema', 'Distribution', 'Attaché de presse', 'Journalistes, projections, interviews.', null, false, 'scaleup', false, 167, 1),
  ('cinema', 'Distribution', 'Responsable marketing', 'Campagne, affiche, bande-annonce, budget média.', null, false, 'scaleup', false, 168, 1),
  ('cinema', 'Distribution', 'Concepteur d''affiches', 'L''image qui résume le film sur un mur.', null, false, 'scaleup', false, 169, 1),
  ('cinema', 'Distribution', 'Community manager', 'Le public en ligne, avant, pendant, après.', null, false, 'scaleup', false, 170, 1),
  ('cinema', 'Public', 'Panel spectateurs', 'Regarde comme un spectateur, dit où il s''ennuie et où il pleure.', null, false, 'startup', false, 171, 3),
  ('cinema', 'Public', 'Analyste d''audience', 'Qui regarde, où, jusqu''où, et pourquoi ils décrochent.', null, false, 'scaleup', false, 172, 1),
  ('juridique', 'Direction', 'Associé directeur', 'Répond des avis rendus, tient les clients, arbitre les conflits d''intérêts.', null, false, 'cocon', true, 100, 1),
  ('juridique', 'Direction', 'Associé', 'Dirige une pratique; signe les avis de son domaine.', null, false, 'startup', false, 101, 2),
  ('juridique', 'Direction', 'Secrétaire général', 'Le cabinet comme entreprise: finances, personnes, outils.', null, false, 'scaleup', false, 102, 1),
  ('juridique', 'Direction', 'Responsable des conflits d''intérêts', 'Vérifie avant chaque dossier qu''on peut le prendre.', null, false, 'scaleup', false, 103, 1),
  ('juridique', 'Contrats', 'Avocat droit des sociétés', 'Création, statuts, pactes, assemblées, cessions.', null, false, 'cocon', false, 104, 1),
  ('juridique', 'Contrats', 'Avocat contrats commerciaux', 'Conditions générales, distribution, prestations, responsabilité.', null, false, 'cocon', false, 105, 1),
  ('juridique', 'Contrats', 'Avocat fusions-acquisitions', 'Audit, garanties, prix, closing.', null, false, 'scaleup', false, 106, 1),
  ('juridique', 'Contrats', 'Avocat capital-risque', 'Levées de fonds, BSA, pactes d''investisseurs.', null, false, 'startup', false, 107, 1),
  ('juridique', 'Contrats', 'Avocat distribution et franchise', 'Réseaux, exclusivités, rupture de relations commerciales.', null, false, 'scaleup', false, 108, 1),
  ('juridique', 'Contrats', 'Avocat droit de la concurrence', 'Ententes, positions dominantes, contrôle des concentrations.', null, false, 'scaleup', false, 109, 1),
  ('juridique', 'Contrats', 'Relecteur de contrats', 'Lit chaque clause, signale ce qui coûte.', null, false, 'startup', false, 110, 2),
  ('juridique', 'Propriété', 'Avocat marques et dessins', 'Dépôt, surveillance, opposition, contrefaçon.', null, false, 'startup', false, 111, 1),
  ('juridique', 'Propriété', 'Conseil en brevets', 'Brevetabilité, rédaction, dépôt, extension.', null, false, 'startup', false, 112, 1),
  ('juridique', 'Propriété', 'Ingénieur brevets', 'Comprend l''invention et l''écrit en revendications.', null, false, 'scaleup', false, 113, 2),
  ('juridique', 'Propriété', 'Avocat droit d''auteur et logiciels', 'Licences, code, contenus, open source.', null, false, 'startup', false, 114, 1),
  ('juridique', 'Propriété', 'Veille contrefaçon', 'Surveille les marchés et les plateformes; signale, fait retirer.', null, false, 'scaleup', false, 115, 1),
  ('juridique', 'Données', 'Avocat protection des données', 'RGPD et équivalents: bases légales, transferts, registres.', null, false, 'startup', false, 116, 1),
  ('juridique', 'Données', 'Délégué à la protection des données', 'Le référent officiel: registre, analyses d''impact, autorité.', null, false, 'scaleup', false, 117, 1),
  ('juridique', 'Données', 'Avocat droit du numérique et plateformes', 'Marketplaces, responsabilité des hébergeurs, DSA, consommateurs en ligne.', null, false, 'startup', false, 118, 1),
  ('juridique', 'Données', 'Avocat cybersécurité et incidents', 'Que faire dans les 72 heures après une fuite.', null, false, 'scaleup', false, 119, 1),
  ('juridique', 'Données', 'Avocat intelligence artificielle', 'Règlement IA, responsabilité, données d''entraînement.', null, false, 'scaleup', false, 120, 1),
  ('juridique', 'Travail', 'Avocat droit du travail', 'Contrats, licenciements, accords, contentieux prud''homal.', null, false, 'startup', false, 121, 1),
  ('juridique', 'Travail', 'Avocat mobilité internationale', 'Visas, détachements, permis de travail.', null, false, 'scaleup', false, 122, 1),
  ('juridique', 'Travail', 'Avocat rémunération et avantages', 'Actions gratuites, bonus, épargne salariale.', null, false, 'megacorp', false, 123, 1),
  ('juridique', 'Fiscal', 'Avocat fiscaliste', 'Impôt sur les sociétés, structuration, contrôles.', null, false, 'startup', false, 124, 1),
  ('juridique', 'Fiscal', 'Prix de transfert', 'Comment les filiales se facturent entre elles, et ce que l''administration accepte.', null, false, 'scaleup', false, 125, 1),
  ('juridique', 'Fiscal', 'TVA et taxes indirectes internationales', 'TVA, droits d''accises, seuils de vente à distance pays par pays.', null, false, 'scaleup', false, 126, 1),
  ('juridique', 'Fiscal', 'Douanes et commerce international', 'Classement, origine, droits, sanctions.', null, false, 'scaleup', false, 127, 1),
  ('juridique', 'Conformité', 'Responsable de la conformité', 'La carte des règles qui s''appliquent, et qui les respecte.', null, false, 'startup', true, 128, 1),
  ('juridique', 'Conformité', 'Anti-corruption', 'Cadeaux, intermédiaires, cartographie des risques.', null, false, 'scaleup', false, 129, 1),
  ('juridique', 'Conformité', 'Sanctions et contrôle des exportations', 'Avec qui on n''a pas le droit de commercer.', null, false, 'scaleup', false, 130, 1),
  ('juridique', 'Conformité', 'Lutte anti-blanchiment', 'Connaissance client, vigilance, déclarations.', null, false, 'scaleup', false, 131, 1),
  ('juridique', 'Conformité', 'Réglementation des paiements', 'Monnaie électronique, agréments, mobile money, fintech.', null, false, 'startup', false, 132, 1),
  ('juridique', 'Conformité', 'Sécurité des produits et consommateurs', 'Étiquetage, garanties, rappels, droit de rétractation.', null, false, 'scaleup', false, 133, 1),
  ('juridique', 'Contentieux', 'Avocat contentieux commercial', 'Assignations, conclusions, audiences.', null, false, 'startup', false, 134, 1),
  ('juridique', 'Contentieux', 'Avocat arbitrage international', 'Quand le contrat renvoie à un tribunal arbitral.', null, false, 'scaleup', false, 135, 1),
  ('juridique', 'Contentieux', 'Médiateur', 'Trouve l''accord avant le procès.', null, false, 'scaleup', false, 136, 1),
  ('juridique', 'Contentieux', 'Recouvrement', 'Fait payer ce qui est dû, à l''amiable puis en justice.', null, false, 'scaleup', false, 137, 1),
  ('juridique', 'Pays', 'Expert Union européenne', 'Règlements et directives, marché unique, guichets.', null, false, 'scaleup', false, 138, 1),
  ('juridique', 'Pays', 'Expert France', 'Sociétés, travail, fiscalité, consommation en droit français.', null, false, 'scaleup', false, 139, 1),
  ('juridique', 'Pays', 'Expert Royaume-Uni', 'Companies House, TVA, emploi, consommateurs.', null, false, 'scaleup', false, 140, 1),
  ('juridique', 'Pays', 'Expert Allemagne', 'GmbH, Impressum, Handelsregister, protection des données.', null, false, 'scaleup', false, 141, 1),
  ('juridique', 'Pays', 'Expert États-Unis', 'Delaware, taxes de vente par État, emploi, FTC.', null, false, 'scaleup', false, 142, 1),
  ('juridique', 'Pays', 'Expert Canada', 'Fédéral et provinces, Québec, taxes.', null, false, 'scaleup', false, 143, 1),
  ('juridique', 'Pays', 'Expert OHADA', 'Le droit uniforme des affaires dans les dix-sept États membres.', null, false, 'scaleup', false, 144, 1),
  ('juridique', 'Pays', 'Expert Cameroun', 'Immatriculation, fiscalité, emploi, commerce électronique.', null, false, 'scaleup', false, 145, 1),
  ('juridique', 'Pays', 'Expert Nigeria', 'CAC, FIRS, protection des données, paiements.', null, false, 'scaleup', false, 146, 1),
  ('juridique', 'Pays', 'Expert Afrique de l''Est', 'Kenya, Tanzanie, Ouganda, Rwanda, Éthiopie.', null, false, 'megacorp', false, 147, 1),
  ('juridique', 'Pays', 'Expert Maghreb', 'Maroc, Algérie, Tunisie.', null, false, 'megacorp', false, 148, 1),
  ('juridique', 'Pays', 'Expert Afrique du Sud', 'CIPC, SARS, POPIA, consommateurs.', null, false, 'megacorp', false, 149, 1),
  ('juridique', 'Pays', 'Expert Golfe', 'Émirats, Arabie saoudite, Qatar: zones franches et agréments.', null, false, 'megacorp', false, 150, 1),
  ('juridique', 'Pays', 'Expert Inde', 'Sociétés, GST, données, investissements étrangers.', null, false, 'megacorp', false, 151, 1),
  ('juridique', 'Pays', 'Expert Chine', 'Entités étrangères, données, licences, douanes.', null, false, 'megacorp', false, 152, 1),
  ('juridique', 'Pays', 'Expert Japon', 'Sociétés, consommation, données.', null, false, 'megacorp', false, 153, 1),
  ('juridique', 'Pays', 'Expert Asie du Sud-Est', 'Singapour, Indonésie, Vietnam, Philippines.', null, false, 'megacorp', false, 154, 1),
  ('juridique', 'Pays', 'Expert Brésil', 'CNPJ, fiscalité fédérale et des États, LGPD.', null, false, 'megacorp', false, 155, 1),
  ('juridique', 'Pays', 'Expert Amérique latine', 'Mexique, Colombie, Chili, Argentine.', null, false, 'megacorp', false, 156, 1),
  ('juridique', 'Pays', 'Expert Australie', 'ASIC, GST, consommateurs, données.', null, false, 'megacorp', false, 157, 1),
  ('juridique', 'Support', 'Parajuriste', 'Recherches, pièces, formalités, dépôts.', null, false, 'startup', false, 158, 3),
  ('juridique', 'Support', 'Juriste d''entreprise', 'Le quotidien juridique côté client: contrats courants, questions rapides.', null, false, 'startup', false, 159, 1),
  ('juridique', 'Support', 'Veille réglementaire', 'Ce qui change dans la loi, avant que ça s''applique.', null, false, 'startup', false, 160, 1),
  ('juridique', 'Support', 'Documentaliste juridique', 'Jurisprudence, doctrine, textes: la bonne source, la bonne version.', null, false, 'scaleup', false, 161, 1),
  ('juridique', 'Support', 'Traducteur juridique', 'Un contrat traduit doit dire exactement la même chose.', null, false, 'scaleup', false, 162, 2),
  ('juridique', 'Support', 'Gestion des connaissances', 'Modèles de clauses, précédents, ce que le cabinet a déjà plaidé.', null, false, 'scaleup', false, 163, 1),
  ('juridique', 'Support', 'Facturation et secrétariat', 'Temps passé, factures, courriers, délais.', null, false, 'scaleup', false, 164, 1),
  ('recherche', 'Direction', 'Directeur adjoint', 'Les moyens, les recrutements, les partenariats; libère le directeur pour la science.', null, false, 'scaleup', false, 100, 1),
  ('recherche', 'Direction', 'Comité scientifique', 'Évalue le programme une fois par an; dit ce qu''il faut arrêter.', null, false, 'scaleup', false, 101, 1),
  ('recherche', 'Direction', 'Responsable administratif', 'Contrats, achats, missions, budget.', null, false, 'scaleup', false, 102, 1),
  ('recherche', 'Chercheurs', 'Chercheur principal', 'Mène une ligne de recherche: hypothèses, équipe, publications.', null, false, 'startup', false, 103, 2),
  ('recherche', 'Chercheurs', 'Chercheur senior', 'Autonome sur son sujet; encadre les plus jeunes.', null, false, 'scaleup', false, 104, 2),
  ('recherche', 'Chercheurs', 'Post-doctorant', 'Deux à trois ans sur un projet précis, avec résultats publiés.', null, false, 'startup', false, 105, 4),
  ('recherche', 'Chercheurs', 'Doctorant', 'Trois ans, une thèse, une contribution originale.', null, false, 'startup', false, 106, 6),
  ('recherche', 'Chercheurs', 'Ingénieur de recherche', 'Fait exister l''expérience: montage, code, instruments.', null, false, 'startup', false, 107, 2),
  ('recherche', 'Chercheurs', 'Assistant de recherche', 'Collecte, saisie, premiers traitements.', null, false, 'scaleup', false, 108, 3),
  ('recherche', 'Chercheurs', 'Chercheur invité', 'Vient d''ailleurs pour six mois; apporte une méthode qu''on n''a pas.', null, false, 'megacorp', false, 109, 1),
  ('recherche', 'Veille', 'Veilleur brevets', 'Ce qui est déjà protégé, par qui, jusqu''à quand.', null, false, 'scaleup', false, 110, 1),
  ('recherche', 'Veille', 'Revue systématique', 'Cartographie toute la littérature sur une question, sans en oublier.', null, false, 'startup', false, 111, 1),
  ('recherche', 'Veille', 'Analyste de tendances', 'Où va le domaine; ce que financent les autres.', null, false, 'scaleup', false, 112, 1),
  ('recherche', 'Méthode', 'Méthodologiste', 'Le protocole est-il capable de répondre à la question ? Sinon, il le dit.', null, false, 'startup', false, 113, 1),
  ('recherche', 'Méthode', 'Concepteur d''expériences', 'Taille d''échantillon, groupes, randomisation, puissance.', null, false, 'startup', false, 114, 1),
  ('recherche', 'Méthode', 'Responsable des données', 'Où sont les données, qui y accède, comment elles sont nommées.', null, false, 'scaleup', false, 115, 1),
  ('recherche', 'Méthode', 'Ingénieur données', 'Pipelines, formats, versions, reproductibilité.', null, false, 'scaleup', false, 116, 1),
  ('recherche', 'Méthode', 'Ingénieur apprentissage automatique', 'Modèles sur les données du laboratoire; validation croisée honnête.', null, false, 'scaleup', false, 117, 1),
  ('recherche', 'Méthode', 'Spécialiste réplication', 'Refait l''expérience des autres avant qu''on s''appuie dessus.', null, false, 'scaleup', false, 118, 1),
  ('recherche', 'Expérience', 'Responsable de laboratoire', 'Sécurité, matériel, planning des paillasses.', null, false, 'scaleup', false, 119, 1),
  ('recherche', 'Expérience', 'Technicien de laboratoire', 'Prépare, mesure, entretient, note.', null, false, 'scaleup', false, 120, 3),
  ('recherche', 'Expérience', 'Ingénieur instrumentation', 'Fait fonctionner et calibrer les instruments.', null, false, 'scaleup', false, 121, 1),
  ('recherche', 'Expérience', 'Responsable calcul haute performance', 'Le cluster, les files d''attente, les coûts de calcul.', null, false, 'scaleup', false, 122, 1),
  ('recherche', 'Expérience', 'Développeur scientifique', 'Le code de l''expérience, testé et versionné.', null, false, 'startup', false, 123, 2),
  ('recherche', 'Rédaction', 'Rédacteur scientifique', 'Transforme les résultats en article soumis.', null, false, 'startup', false, 124, 1),
  ('recherche', 'Rédaction', 'Relecteur par les pairs', 'Lit l''article comme un rapporteur hostile, avant la soumission.', null, false, 'startup', false, 125, 2),
  ('recherche', 'Rédaction', 'Illustrateur scientifique', 'Figures, schémas, graphiques lisibles.', null, false, 'scaleup', false, 126, 1),
  ('recherche', 'Rédaction', 'Vulgarisateur', 'Explique le résultat à quelqu''un qui n''est pas du domaine.', null, false, 'scaleup', false, 127, 1),
  ('recherche', 'Rédaction', 'Traducteur scientifique', 'L''article dans la langue du journal, sans perdre la précision.', null, false, 'megacorp', false, 128, 1),
  ('recherche', 'Qualité', 'Comité d''éthique', 'Consentement, animaux, données sensibles: ce qu''on a le droit de faire.', null, false, 'startup', false, 129, 1),
  ('recherche', 'Qualité', 'Intégrité scientifique', 'Plagiat, fabrication, conflits d''intérêts.', null, false, 'scaleup', false, 130, 1),
  ('recherche', 'Qualité', 'Responsable qualité', 'Procédures, traçabilité, audits.', null, false, 'scaleup', false, 131, 1),
  ('recherche', 'Qualité', 'Délégué à la protection des données', 'Données de participants: registre, anonymisation, durée.', null, false, 'scaleup', false, 132, 1),
  ('recherche', 'Financement', 'Partenariats industriels', 'Les entreprises qui financent et ce qu''elles attendent.', null, false, 'scaleup', false, 133, 1),
  ('recherche', 'Financement', 'Valorisation et transfert', 'Brevets, licences, création d''entreprise à partir des résultats.', null, false, 'scaleup', false, 134, 1),
  ('recherche', 'Financement', 'Gestionnaire de projets financés', 'Livrables, rapports, dépenses éligibles.', null, false, 'scaleup', false, 135, 1),
  ('recherche', 'Domaines', 'Biologie et santé', 'Cellules, organismes, essais cliniques.', null, false, 'scaleup', false, 136, 1),
  ('recherche', 'Domaines', 'Physique', 'Matière, énergie, mesure.', null, false, 'scaleup', false, 137, 1),
  ('recherche', 'Domaines', 'Chimie et matériaux', 'Synthèse, caractérisation, propriétés.', null, false, 'scaleup', false, 138, 1),
  ('recherche', 'Domaines', 'Informatique et intelligence artificielle', 'Algorithmes, systèmes, apprentissage.', null, false, 'startup', false, 139, 1),
  ('recherche', 'Domaines', 'Mathématiques', 'Preuves, modèles, statistiques.', null, false, 'scaleup', false, 140, 1),
  ('recherche', 'Domaines', 'Sciences sociales', 'Enquêtes, entretiens, terrains.', null, false, 'scaleup', false, 141, 1),
  ('recherche', 'Domaines', 'Économie', 'Marchés, incitations, données de panel.', null, false, 'scaleup', false, 142, 1),
  ('recherche', 'Domaines', 'Climat et environnement', 'Modèles, mesures, scénarios.', null, false, 'megacorp', false, 143, 1),
  ('recherche', 'Domaines', 'Neurosciences', 'Cerveau, comportement, imagerie.', null, false, 'megacorp', false, 144, 1),
  ('recherche', 'Domaines', 'Agronomie', 'Sols, cultures, rendements, climat.', null, false, 'megacorp', false, 145, 1),
  ('croissance', 'Direction', 'Directeur d''agence', 'Clients, marges, talents; répond des résultats.', null, false, 'startup', false, 100, 1),
  ('croissance', 'Direction', 'Directeur de clientèle', 'Tient chaque compte; sait ce que le client pense avant qu''il le dise.', null, false, 'startup', false, 101, 1),
  ('croissance', 'Direction', 'Chef de projet', 'Brief, planning, livraison, budget.', null, false, 'startup', false, 102, 2),
  ('croissance', 'Direction', 'Planneur stratégique', 'Comprend le marché et le public; écrit le brief que la création suit.', null, false, 'startup', false, 103, 1),
  ('croissance', 'Marque', 'Directeur de création', 'Le message et la forme; refuse le médiocre.', null, false, 'startup', true, 104, 1),
  ('croissance', 'Marque', 'Concepteur-rédacteur', 'Le titre, l''accroche, le texte qui fait agir.', null, false, 'startup', false, 105, 2),
  ('croissance', 'Marque', 'Directeur artistique', 'L''image, la mise en page, la cohérence visuelle.', null, false, 'startup', false, 106, 2),
  ('croissance', 'Marque', 'Motion designer', 'Animation, habillage, formats courts.', null, false, 'scaleup', false, 107, 1),
  ('croissance', 'Marque', 'Photographe', 'Produits, portraits, ambiances — de vraies images.', null, false, 'scaleup', false, 108, 1),
  ('croissance', 'Marque', 'Responsable de marque', 'Positionnement, ton, cohérence sur tous les canaux.', null, false, 'scaleup', false, 109, 1),
  ('croissance', 'Marque', 'Chercheur utilisateur', 'Entretiens, tests, ce que les gens font vraiment.', null, false, 'scaleup', false, 110, 1),
  ('croissance', 'Acquisition', 'Responsable SEO', 'Être trouvé: mots-clés, contenus, technique, liens.', null, false, 'startup', false, 111, 1),
  ('croissance', 'Acquisition', 'Responsable publicité payante', 'Google, Meta, TikTok: enchères, audiences, coût par acquisition.', null, false, 'startup', false, 112, 2),
  ('croissance', 'Acquisition', 'Responsable conversion', 'Le taux de conversion, page par page, test par test.', null, false, 'scaleup', false, 113, 1),
  ('croissance', 'Acquisition', 'Responsable app stores', 'Fiche, mots-clés, visuels, notes: le référencement dans les magasins d''applications.', null, false, 'scaleup', false, 114, 1),
  ('croissance', 'Acquisition', 'Responsable partenariats', 'Co-marketing, affiliation, distribution croisée.', null, false, 'scaleup', false, 115, 1),
  ('croissance', 'Réseaux', 'Responsable réseaux sociaux', 'Ligne éditoriale, calendrier, formats par plateforme.', null, false, 'startup', false, 116, 1),
  ('croissance', 'Réseaux', 'Responsable influence', 'Trouve, négocie, mesure les créateurs.', null, false, 'scaleup', false, 117, 1),
  ('croissance', 'Réseaux', 'Relations presse', 'Journalistes, communiqués, retombées.', null, false, 'scaleup', false, 118, 1),
  ('croissance', 'Réseaux', 'Événementiel', 'Salons, lancements, rencontres.', null, false, 'megacorp', false, 119, 1),
  ('croissance', 'Contenu', 'Responsable e-mailing et CRM', 'Séquences, segments, relances, désinscription propre.', null, false, 'startup', false, 120, 1),
  ('croissance', 'Contenu', 'Automatisation marketing', 'Les scénarios qui tournent seuls: bienvenue, panier abandonné, réactivation.', null, false, 'scaleup', false, 121, 1),
  ('croissance', 'Contenu', 'Responsable localisation', 'Le message dans la langue et la culture de chaque marché.', null, false, 'scaleup', false, 122, 1),
  ('croissance', 'Contenu', 'Product marketing', 'Positionnement d''une fonctionnalité, lancement, argumentaire.', null, false, 'scaleup', false, 123, 1),
  ('croissance', 'Ventes', 'Prospecteur', 'Trouve les bons contacts, écrit, relance, prend le rendez-vous.', null, false, 'startup', false, 124, 3),
  ('croissance', 'Ventes', 'Commercial', 'Mène le rendez-vous, négocie, signe.', null, false, 'startup', false, 125, 2),
  ('croissance', 'Ventes', 'Responsable succès client', 'Onboarding, usage, renouvellement, montée en gamme.', null, false, 'scaleup', false, 126, 2),
  ('croissance', 'Ventes', 'Analyste marketing', 'Attribution, tableaux de bord, coût par canal.', null, false, 'startup', false, 127, 1),
  ('produit', 'Direction', 'Directeur technique', 'Architecture, choix techniques, dette; répond de ce qui tourne.', null, false, 'cocon', true, 100, 1),
  ('produit', 'Direction', 'Directeur produit', 'Vision, priorités, ce qu''on ne fera pas.', null, false, 'startup', true, 101, 1),
  ('produit', 'Direction', 'VP ingénierie', 'Les équipes, les recrutements, la cadence de livraison.', null, false, 'scaleup', false, 102, 1),
  ('produit', 'Direction', 'Responsable d''équipe', 'Six à dix ingénieurs; leur progression et leur livraison.', null, false, 'scaleup', false, 103, 3),
  ('produit', 'Produit', 'Chef de produit', 'Découverte, spécifications, arbitrages avec les utilisateurs.', null, false, 'startup', false, 104, 2),
  ('produit', 'Produit', 'Product owner', 'Le backlog, les critères d''acceptation, la démo.', null, false, 'scaleup', false, 105, 2),
  ('produit', 'Produit', 'Designer produit', 'Parcours, écrans, composants; ce que l''utilisateur touche.', null, false, 'startup', false, 106, 2),
  ('produit', 'Produit', 'Chercheur utilisateur', 'Entretiens, tests d''utilisabilité, ce qui bloque vraiment.', null, false, 'scaleup', false, 107, 1),
  ('produit', 'Produit', 'Rédacteur d''interface', 'Chaque libellé, chaque message d''erreur, dans la langue de l''utilisateur.', null, false, 'scaleup', false, 108, 1),
  ('produit', 'Produit', 'Responsable accessibilité', 'Utilisable par tous: lecteurs d''écran, contrastes, clavier.', null, false, 'scaleup', false, 109, 1),
  ('produit', 'Produit', 'Responsable localisation', 'Langues, devises, formats de date: le produit partout.', null, false, 'scaleup', false, 110, 1),
  ('produit', 'Ingénierie', 'Développeur front', 'L''interface web: composants, états, performance perçue.', null, false, 'cocon', false, 111, 4),
  ('produit', 'Ingénierie', 'Développeur back', 'Services, base de données, API, logique métier.', null, false, 'cocon', false, 112, 4),
  ('produit', 'Ingénierie', 'Développeur mobile iOS', 'L''application iPhone et iPad, native ou hybride.', null, false, 'startup', false, 113, 2),
  ('produit', 'Ingénierie', 'Développeur mobile Android', 'L''application Android, sur tous les téléphones qui existent.', null, false, 'startup', false, 114, 2),
  ('produit', 'Ingénierie', 'Ingénieur full-stack', 'De la base à l''écran; utile quand l''équipe est petite.', null, false, 'cocon', false, 115, 3),
  ('produit', 'Ingénierie', 'Architecte', 'Les frontières entre services, les contrats, ce qui doit durer.', null, false, 'scaleup', false, 116, 1),
  ('produit', 'Ingénierie', 'Rédacteur technique', 'Documentation, guides, référence d''API.', null, false, 'scaleup', false, 117, 1),
  ('produit', 'Ingénierie', 'Relations développeurs', 'Les développeurs externes qui construisent sur le produit.', null, false, 'megacorp', false, 118, 1),
  ('produit', 'Qualité', 'Ingénieur qualité', 'Stratégie de test, automatisation, ce qu''on ne teste pas et pourquoi.', null, false, 'startup', false, 119, 2),
  ('produit', 'Qualité', 'Testeur', 'Utilise le produit comme un client pressé et casse tout.', null, false, 'startup', false, 120, 2),
  ('produit', 'Qualité', 'Ingénieur performance', 'Temps de réponse, charge, ce qui ralentit.', null, false, 'scaleup', false, 121, 1),
  ('produit', 'Infrastructure', 'Ingénieur fiabilité', 'Disponibilité, astreinte, incidents, post-mortems.', null, false, 'scaleup', false, 122, 2),
  ('produit', 'Infrastructure', 'Ingénieur DevOps', 'Déploiement, intégration continue, environnements.', null, false, 'startup', false, 123, 2),
  ('produit', 'Infrastructure', 'Ingénieur sécurité', 'Menaces, revues, secrets, réponse aux incidents.', null, false, 'startup', false, 124, 1),
  ('produit', 'Infrastructure', 'Ingénieur plateforme', 'Les outils internes que les autres équipes utilisent.', null, false, 'megacorp', false, 125, 2),
  ('produit', 'Données', 'Ingénieur données', 'Pipelines, entrepôt, qualité des données.', null, false, 'startup', false, 126, 2),
  ('produit', 'Données', 'Analyste données', 'Tableaux de bord, requêtes, réponses aux questions du produit.', null, false, 'startup', false, 127, 2),
  ('produit', 'Données', 'Data scientist', 'Modèles, expérimentations, prédictions.', null, false, 'scaleup', false, 128, 1),
  ('produit', 'IA', 'Ingénieur IA appliquée', 'Intègre les modèles dans le produit: prompts, évaluation, coûts.', null, false, 'startup', false, 129, 2),
  ('produit', 'IA', 'Ingénieur apprentissage automatique', 'Entraîne, évalue, déploie, surveille.', null, false, 'scaleup', false, 130, 1),
  ('produit', 'Opérations', 'Scrum master', 'La cadence, les rituels, les obstacles levés.', null, false, 'scaleup', false, 131, 1),
  ('produit', 'Opérations', 'Support technique', 'Répond aux clients, reproduit les bugs, remonte.', null, false, 'startup', false, 132, 2)
) as v(modele, departement, poste, mandat, agent_cle, a_ecrire, des_la_taille, est_directeur, ordre, poids)
where not exists (
  select 1 from public.studio_modele_postes p where p.modele = v.modele and lower(p.poste) = lower(v.poste)
);

-- Les postes qu'on avait marqués « à écrire » dans 0136 ont maintenant un
-- mandat qui suffit: on les allume.
update public.studio_modele_postes set a_ecrire = false where a_ecrire and mandat is not null and length(mandat) > 10;

-- Le catalogue contenait un gabarit (« Agent Name ») pris pour un agent.
delete from public.studio_modele_postes where agent_cle = 'agent-name';

-- Les postes venus du catalogue « c-level » portaient le préfixe technique « Cs ».
update public.studio_modele_postes set poste = regexp_replace(poste, '^Cs ', '') where poste like 'Cs %';

-- Un directeur par département suffit: dans un modèle, un poste directeur
-- reste unique, les nouveaux directeurs écrits ici ne doublent pas ceux de 0136.
