-- Les intitulés de postes restés en anglais, traduits (plan complet, B10).
--
-- Les métiers venus du catalogue de compétences sur GitHub gardaient leur
-- nom d'origine: « Devils Advocate », « Startup Cto », « Seo Snippet Hunter ».
-- Traduits un par un, à la main, en français de métier; les noms de
-- technologies restent (React, Kubernetes). Seul le catalogue change: les
-- agents déjà recrutés gardent leur intitulé.
with t(avant, apres) as (values
  ('Accessibility Expert', 'Expert accessibilité'),
  ('Accessibility Tester', 'Testeur accessibilité'),
  ('Ad Security Reviewer', 'Contrôleur sécurité Active Directory'),
  ('Aeo', 'Optimisation pour les moteurs de réponse (IA)'),
  ('Agent Installer', 'Installateur d''agents'),
  ('Agent Orchestration Context Manager', 'Gestionnaire du contexte des agents'),
  ('Agent Organizer', 'Organisateur des agents'),
  ('Agile Product Owner', 'Product owner agile'),
  ('Ai Act Compliance', 'Conformité AI Act'),
  ('Ai Writing Auditor', 'Relecteur des textes écrits par l''IA'),
  ('Angular Architect', 'Architecte Angular'),
  ('Api Designer', 'Concepteur d''API'),
  ('Api Scaffolding Backend Architect', 'Architecte des fondations d''API'),
  ('Api Scaffolding Graphql Architect', 'Architecte des fondations GraphQL'),
  ('Architect Reviewer', 'Relecteur d''architecture'),
  ('Auth Integration Engineer', 'Ingénieur authentification'),
  ('Azure Infra Engineer', 'Ingénieur infrastructure Azure'),
  ('Backend Developer', 'Développeur backend'),
  ('Backend Development Backend Architect', 'Architecte backend'),
  ('Backend Development Graphql Architect', 'Architecte GraphQL (backend)'),
  ('Backend Development Performance Engineer', 'Ingénieur performance backend'),
  ('Backend Development Security Auditor', 'Auditeur sécurité backend'),
  ('Backend Development Tdd Orchestrator', 'Pilote des tests d''abord (TDD)'),
  ('Backend Development Test Automator', 'Automaticien de tests backend'),
  ('Backend Engineer', 'Ingénieur backend'),
  ('Bizops Orchestrator', 'Pilote des opérations business'),
  ('Blockchain Developer', 'Développeur blockchain'),
  ('Build Engineer', 'Ingénieur de build'),
  ('Business Analyst', 'Analyste métier'),
  ('Caio Advisor', 'Conseiller du directeur de l''IA'),
  ('Cco Advisor', 'Conseiller du directeur commercial'),
  ('Chaos Engineer', 'Ingénieur tests de résilience'),
  ('Cli Developer', 'Développeur d''outils en ligne de commande'),
  ('Cloud Architect', 'Architecte cloud'),
  ('Cloud Infrastructure Cloud Architect', 'Architecte infrastructure cloud'),
  ('Cloud Infrastructure Deployment Engineer', 'Ingénieur déploiement cloud'),
  ('Cloud Infrastructure Kubernetes Architect', 'Architecte Kubernetes (cloud)'),
  ('Cloud Infrastructure Network Engineer', 'Ingénieur réseau cloud'),
  ('Cloud Infrastructure Terraform Specialist', 'Spécialiste Terraform (cloud)'),
  ('Code Reviewer', 'Relecteur de code'),
  ('Codebase Orchestrator', 'Gardien de la base de code'),
  ('Competitive Analyst', 'Analyste concurrence'),
  ('Compliance Auditor', 'Auditeur conformité'),
  ('Compliance Officer', 'Responsable conformité'),
  ('Content Creator', 'Créateur de contenu'),
  ('Content Marketer', 'Marketeur de contenu'),
  ('Content Quality Editor', 'Éditeur qualité des contenus'),
  ('Content Strategist', 'Stratège de contenu'),
  ('Context Manager', 'Gestionnaire de contexte'),
  ('Csharp Developer', 'Développeur C#'),
  ('Cto Advisor', 'Conseiller du directeur technique'),
  ('Customer Success Manager', 'Responsable succès client (compte)'),
  ('Customer Support', 'Support client'),
  ('Data Analyst', 'Analyste de données'),
  ('Data Engineer', 'Ingénieur données'),
  ('Data Researcher', 'Chercheur en données'),
  ('Database Optimizer', 'Optimiseur de bases de données'),
  ('Demand Gen Specialist', 'Spécialiste génération de demande'),
  ('Dependency Manager', 'Gestionnaire des dépendances'),
  ('Deployment Engineer', 'Ingénieur déploiement'),
  ('Design System Architect', 'Architecte du design system'),
  ('Devils Advocate', 'Avocat du diable (produit)'),
  ('Devops Engineer', 'Ingénieur DevOps'),
  ('Devops Incident Responder', 'Répondant incidents DevOps'),
  ('Directeur de mission (CEO advisor)', 'Directeur de mission (conseil du dirigeant)'),
  ('Django Developer', 'Développeur Django'),
  ('Docker Expert', 'Expert Docker'),
  ('Docs Drift Editor', 'Gardien de la documentation à jour'),
  ('Documentation Engineer', 'Ingénieur documentation'),
  ('Dotnet Core Expert', 'Expert .NET Core'),
  ('Dotnet Framework 4 8 Expert', 'Expert .NET Framework 4.8'),
  ('Dx Optimizer', 'Optimiseur de l''expérience développeur'),
  ('Elixir Expert', 'Expert Elixir'),
  ('Email Deliverability Engineer', 'Ingénieur délivrabilité des e-mails'),
  ('Engineering Lead', 'Responsable d''équipe technique'),
  ('Error Coordinator', 'Coordinateur des erreurs'),
  ('Event Sourcing Architect', 'Architecte event sourcing'),
  ('Expo React Native Expert', 'Expert Expo et React Native'),
  ('Fastapi Developer', 'Développeur FastAPI'),
  ('Fda Qsr Auditor', 'Auditeur réglementation FDA'),
  ('Finance Lead', 'Responsable finance (équipe)'),
  ('Financial Analyst', 'Analyste financier'),
  ('Fintech Engineer', 'Ingénieur fintech'),
  ('Flutter Expert', 'Expert Flutter'),
  ('Frontend Developer', 'Développeur frontend'),
  ('Frontend Engineer', 'Ingénieur frontend'),
  ('Full Stack Orchestration Deployment Engineer', 'Ingénieur déploiement full stack'),
  ('Full Stack Orchestration Performance Engineer', 'Ingénieur performance full stack'),
  ('Full Stack Orchestration Security Auditor', 'Auditeur sécurité full stack'),
  ('Fullstack Developer', 'Développeur full stack'),
  ('Fullstack Engineer', 'Ingénieur full stack'),
  ('Game Developer', 'Développeur de jeux'),
  ('Gdpr Ccpa Compliance', 'Conformité RGPD et CCPA'),
  ('General Counsel Advisor', 'Conseiller du directeur juridique'),
  ('Git Workflow Manager', 'Responsable des flux Git'),
  ('Graphql Architect', 'Architecte GraphQL'),
  ('Grill Master', 'Questionneur exigeant'),
  ('Growth Loops', 'Boucles de croissance'),
  ('Growth Marketer', 'Marketeur croissance'),
  ('Hipaa Compliance', 'Conformité HIPAA (santé)'),
  ('Hive Tester', 'Testeur en essaim'),
  ('Hub Coordinator', 'Coordinateur central'),
  ('Hybrid Cloud Architect', 'Architecte cloud hybride'),
  ('Incident Responder', 'Répondant incidents'),
  ('Ios Developer', 'Développeur iOS'),
  ('Iot Engineer', 'Ingénieur objets connectés'),
  ('It Ops Orchestrator', 'Pilote des opérations informatiques'),
  ('Java Architect', 'Architecte Java'),
  ('Karpathy Reviewer', 'Relecteur de code IA'),
  ('Kotlin Specialist', 'Spécialiste Kotlin'),
  ('Kubernetes Specialist', 'Spécialiste Kubernetes'),
  ('Laravel Specialist', 'Spécialiste Laravel'),
  ('Legal Advisor', 'Conseiller juridique (produit)'),
  ('License Engineer', 'Ingénieur licences logicielles'),
  ('Linkedin Editor', 'Éditeur LinkedIn'),
  ('Linkedin Orchestrator', 'Pilote LinkedIn'),
  ('Llm Architect', 'Architecte modèles de langage'),
  ('Machine Learning Engineer', 'Ingénieur apprentissage automatique'),
  ('Market Researcher', 'Chargé d''études de marché'),
  ('Mcp Developer', 'Développeur MCP'),
  ('Memory Analyst', 'Analyste de la mémoire des agents'),
  ('Memory Curator', 'Gardien de la mémoire'),
  ('Memory Engineer', 'Ingénieur mémoire des agents'),
  ('Microservices Architect', 'Architecte microservices'),
  ('Migration Planner', 'Planificateur de migrations'),
  ('Ml Engineer', 'Ingénieur ML'),
  ('Mlops Engineer', 'Ingénieur MLOps'),
  ('Mobile App Developer', 'Développeur d''applications mobiles'),
  ('Mobile Developer', 'Développeur mobile'),
  ('Multi Agent Coordinator', 'Coordinateur multi-agents'),
  ('Multi Platform Apps Backend Architect', 'Architecte backend multiplateforme'),
  ('Multi Platform Apps Frontend Developer', 'Développeur frontend multiplateforme'),
  ('Multi Platform Apps Mobile Developer', 'Développeur mobile multiplateforme'),
  ('Network Engineer', 'Ingénieur réseau'),
  ('Nextjs Developer', 'Développeur Next.js'),
  ('Nlp Engineer', 'Ingénieur traitement du langage'),
  ('Node Specialist', 'Spécialiste Node.js'),
  ('Penetration Tester', 'Testeur d''intrusion'),
  ('Performance Engineer', 'Ingénieur performance'),
  ('Performance Monitor', 'Surveillant des performances'),
  ('Platform Engineer', 'Ingénieur plateforme'),
  ('Pm Orchestrator', 'Pilote de la gestion de projet'),
  ('Powershell 5 1 Expert', 'Expert PowerShell 5.1'),
  ('Powershell 7 Expert', 'Expert PowerShell 7'),
  ('Powershell Module Architect', 'Architecte modules PowerShell'),
  ('Powershell Security Hardening', 'Durcissement sécurité PowerShell'),
  ('Powershell Ui Architect', 'Architecte interfaces PowerShell'),
  ('Product Analyst', 'Analyste produit'),
  ('Product Manager', 'Chef de produit'),
  ('Product Orchestrator', 'Pilote produit'),
  ('Product Strategist', 'Stratège produit'),
  ('Product marketing', 'Marketing produit'),
  ('Project Manager', 'Chef de projet'),
  ('Qa Expert', 'Expert qualité logicielle'),
  ('Quant Analyst', 'Analyste quantitatif (quant)'),
  ('Rails Expert', 'Expert Ruby on Rails'),
  ('React Specialist', 'Spécialiste React'),
  ('Readme Generator', 'Rédacteur de README'),
  ('Refactoring Specialist', 'Spécialiste refonte de code'),
  ('Reinforcement Learning Engineer', 'Ingénieur apprentissage par renforcement'),
  ('Research Analyst', 'Analyste recherche'),
  ('Risk Manager', 'Gestionnaire des risques'),
  ('Rust Engineer', 'Ingénieur Rust'),
  ('Sales Engineer', 'Ingénieur commercial'),
  ('Scientific Literature Researcher', 'Documentaliste scientifique'),
  ('Scraping Architect', 'Architecte collecte web'),
  ('Scrum Master', 'Scrum master'),
  ('Search Specialist', 'Spécialiste recherche d''information'),
  ('Security Auditor', 'Auditeur sécurité (code)'),
  ('Security Engineer', 'Ingénieur sécurité'),
  ('Senior Engineer', 'Ingénieur senior'),
  ('Seo Authority Builder', 'SEO — autorité du site'),
  ('Seo Cannibalization Detector', 'SEO — pages qui se concurrencent'),
  ('Seo Content Refresher', 'SEO — mise à jour des contenus'),
  ('Seo Keyword Strategist', 'SEO — stratégie de mots-clés'),
  ('Seo Meta Optimizer', 'SEO — titres et descriptions'),
  ('Seo Snippet Hunter', 'SEO — extraits en tête de Google'),
  ('Seo Specialist', 'Spécialiste SEO'),
  ('Seo Structure Architect', 'SEO — structure du site'),
  ('Service Mesh Expert', 'Expert service mesh'),
  ('Slack Expert', 'Expert Slack'),
  ('Soc2 Auditor', 'Auditeur SOC 2'),
  ('Social Publishing Publisher', 'Publication sur les réseaux'),
  ('Spring Boot Engineer', 'Ingénieur Spring Boot'),
  ('Sre Engineer', 'Ingénieur fiabilité (SRE)'),
  ('Startup Analyst', 'Analyste startups'),
  ('Startup Cto', 'Directeur technique de startup'),
  ('Swift Expert', 'Expert Swift'),
  ('Symfony Specialist', 'Spécialiste Symfony'),
  ('Technical Writer', 'Rédacteur technique'),
  ('Terraform Engineer', 'Ingénieur Terraform'),
  ('Terragrunt Expert', 'Expert Terragrunt'),
  ('Test Architect', 'Architecte des tests'),
  ('Threat Modeling Expert', 'Expert modélisation des menaces'),
  ('Tooling Engineer', 'Ingénieur outillage'),
  ('Trend Analyst', 'Analyste tendances'),
  ('Ui Ux Designer', 'Designer UI/UX'),
  ('Ui Ux Tester', 'Testeur UI/UX'),
  ('Ui Visual Validator', 'Contrôleur visuel des interfaces'),
  ('Ux Researcher', 'Chercheur en expérience utilisateur'),
  ('Vector Database Engineer', 'Ingénieur bases vectorielles'),
  ('Visual Asset Generator', 'Générateur de visuels'),
  ('Vue Expert', 'Expert Vue.js'),
  ('Webhook Engineer', 'Ingénieur webhooks'),
  ('Websocket Engineer', 'Ingénieur WebSocket'),
  ('Wordpress Master', 'Expert WordPress'),
  ('Workflow Architect', 'Architecte des flux de travail'),
  ('Workflow Orchestrator', 'Pilote des flux de travail')
)
update public.studio_modele_postes p set poste = t.apres
from t
where p.poste = t.avant
  and not exists (select 1 from public.studio_modele_postes x where x.modele = p.modele and x.poste = t.apres);
