-- 0178 — Le catalogue: « Construire une application de A à Z » (200 postes),
-- et les deux postes qui manquaient à la liste de Beau.
--
-- Beau, 23/09 (conversation avec Gemini) : « les 200 rôles pour construire
-- une application de A à Z » — de l'idée au déploiement, en passant par le
-- design, le code, la base, le paiement, la croissance, le juridique et le
-- support. Écrit à la main (pas généré) : dix départements de vingt postes,
-- un responsable par département, et les postes indispensables ouverts dès
-- la plus petite taille (« cocon »).
--
-- Et les deux postes de la liste de cent que le catalogue n'avait pas encore
-- (vérifié par programme le 23/09) : responsable de l'innovation, asset
-- manager immobilier.
--
-- Données seulement, ajoutées : aucune ligne existante n'est modifiée.

insert into public.studio_modeles (cle, nom, promesse, emoji, niveau, taille_defaut, ordre, actif, concept, effectifs)
values (
  'application-a-z',
  'Construire une application de A à Z',
  'De l''idée à l''application en ligne : produit, design, code, paiement, croissance, juridique, support.',
  '📱',
  'Studio d''application',
  'startup',
  60,
  true,
  'Une application se construit en boucle : on comprend un besoin, on le dessine, on le code, on le met en ligne, on mesure, et on recommence. La Direction & Produit décide quoi construire et pourquoi ; le Design rend chaque écran simple ; le Front-end et le Back-end le construisent ; les Données gardent la base juste et protégée ; les Paiements font rentrer l''argent sans erreur ; la Croissance fait venir et revenir les utilisateurs ; le Juridique et la Sécurité protègent l''entreprise et les données ; le Support écoute et répond ; l''Infrastructure met en ligne sans casser. Le travail circule par tâches courtes, livrées, testées et mesurées.',
  'Seul ou à deux : l''essentiel tient en une quinzaine de rôles. Jeune pousse : 10 à 50. Éditeur établi : 50 à 500. Géant du logiciel : plusieurs milliers.'
)
on conflict (cle) do nothing;

insert into public.studio_modele_postes (modele, departement, poste, mandat, des_la_taille, est_directeur, ordre, poids)
select v.* from (values
  ('application-a-z', 'Direction & Produit', 'Directeur ou directrice produit', 'Tient la vision de l''application, arbitre les priorités et dit non à ce qui ne sert pas l''utilisateur.', 'cocon', true, 1, 1),
  ('application-a-z', 'Direction & Produit', 'Chef de produit', 'Transforme les besoins en fonctionnalités précises, écrit les spécifications et suit leur livraison.', 'cocon', false, 2, 2),
  ('application-a-z', 'Direction & Produit', 'Chercheur ou chercheuse utilisateurs', 'Interroge les futurs utilisateurs, observe leurs usages et ramène des faits plutôt que des opinions.', 'startup', false, 3, 1),
  ('application-a-z', 'Direction & Produit', 'Analyste marché et concurrence', 'Cartographie les concurrents, leurs prix et leurs lancements, et repère les places à prendre.', 'startup', false, 4, 1),
  ('application-a-z', 'Direction & Produit', 'Responsable de la feuille de route', 'Tient la feuille de route à jour, trimestre par trimestre, et la partage avec toute l''équipe.', 'startup', false, 5, 1),
  ('application-a-z', 'Direction & Produit', 'Product owner', 'Découpe le travail en tâches livrables, les ordonne et valide ce qui est terminé.', 'startup', false, 6, 2),
  ('application-a-z', 'Direction & Produit', 'Responsable des indicateurs produit', 'Définit ce qu''on mesure (activation, rétention, conversion) et vérifie que les chiffres sont justes.', 'startup', false, 7, 1),
  ('application-a-z', 'Direction & Produit', 'Responsable des expérimentations', 'Monte des tests A/B propres, avec une hypothèse, un critère de réussite et une conclusion écrite.', 'scaleup', false, 8, 1),
  ('application-a-z', 'Direction & Produit', 'Stratège de modèle économique', 'Choisit comment l''application gagne de l''argent : abonnement, commission, gratuit avec options.', 'cocon', false, 9, 1),
  ('application-a-z', 'Direction & Produit', 'Responsable de l''innovation', 'Repère les usages et technologies qui peuvent changer le produit, les teste en petit et arrête vite ce qui échoue.', 'scaleup', false, 10, 1),
  ('application-a-z', 'Direction & Produit', 'Rédacteur ou rédactrice de spécifications', 'Écrit les parcours, les cas limites et les critères d''acceptation avant que le code commence.', 'startup', false, 11, 1),
  ('application-a-z', 'Direction & Produit', 'Responsable de la voix du client', 'Rassemble les retours du support, des avis et des entretiens, et les transforme en priorités.', 'startup', false, 12, 1),
  ('application-a-z', 'Direction & Produit', 'Chef de projet de lancement', 'Coordonne tout ce qui doit être prêt le jour du lancement : produit, stores, communication, support.', 'startup', false, 13, 1),
  ('application-a-z', 'Direction & Produit', 'Responsable des partenariats produit', 'Négocie les intégrations avec d''autres services qui apportent des utilisateurs ou des fonctions.', 'scaleup', false, 14, 1),
  ('application-a-z', 'Direction & Produit', 'Responsable de la tarification', 'Fixe les prix et les formules, teste leur effet et surveille ce que font les concurrents.', 'startup', false, 15, 1),
  ('application-a-z', 'Direction & Produit', 'Product manager croissance', 'Améliore l''inscription, la première utilisation et le retour des utilisateurs, chiffres à l''appui.', 'scaleup', false, 16, 1),
  ('application-a-z', 'Direction & Produit', 'Product manager plateforme', 'Rend les briques internes (comptes, notifications, paiements) simples à réutiliser par les équipes.', 'scaleup', false, 17, 1),
  ('application-a-z', 'Direction & Produit', 'Responsable de l''accessibilité produit', 'Veille à ce que l''application soit utilisable par tous, y compris avec un lecteur d''écran.', 'scaleup', false, 18, 1),
  ('application-a-z', 'Direction & Produit', 'Responsable de l''internationalisation', 'Prépare l''application pour plusieurs langues, monnaies et pays, sans supposer un seul marché.', 'startup', false, 19, 1),
  ('application-a-z', 'Direction & Produit', 'Coordinateur ou coordinatrice produit', 'Tient les comptes rendus, les décisions et le calendrier des rituels de l''équipe produit.', 'scaleup', false, 20, 1),
  ('application-a-z', 'Design & Expérience', 'Directeur ou directrice du design', 'Garantit une expérience cohérente et belle, du premier écran au dernier e-mail.', 'startup', true, 21, 1),
  ('application-a-z', 'Design & Expérience', 'Designer produit', 'Conçoit les parcours et les écrans, du croquis à la maquette prête à coder.', 'cocon', false, 22, 2),
  ('application-a-z', 'Design & Expérience', 'Designer UX', 'Simplifie les parcours : moins d''étapes, moins d''erreurs, plus de tâches réussies.', 'startup', false, 23, 2),
  ('application-a-z', 'Design & Expérience', 'Designer UI', 'Dessine des écrans lisibles et soignés : typographie, couleurs, espacements, états.', 'startup', false, 24, 2),
  ('application-a-z', 'Design & Expérience', 'Responsable du système de design', 'Tient la bibliothèque de composants et de règles pour que tout se ressemble et se réutilise.', 'scaleup', false, 25, 1),
  ('application-a-z', 'Design & Expérience', 'Designer d''interactions', 'Définit les transitions, retours visuels et micro-animations qui rendent l''app agréable.', 'scaleup', false, 26, 1),
  ('application-a-z', 'Design & Expérience', 'Rédacteur ou rédactrice UX', 'Écrit les boutons, messages d''erreur et textes d''aide : courts, clairs, dans la langue de l''utilisateur.', 'startup', false, 27, 1),
  ('application-a-z', 'Design & Expérience', 'Chercheur ou chercheuse UX', 'Teste les maquettes avec de vrais utilisateurs et dit ce qui bloque, preuves à l''appui.', 'startup', false, 28, 1),
  ('application-a-z', 'Design & Expérience', 'Designer mobile', 'Adapte chaque parcours aux gestes et contraintes d''un téléphone, du petit écran au clavier.', 'startup', false, 29, 1),
  ('application-a-z', 'Design & Expérience', 'Designer graphique', 'Crée les visuels de marque, les icônes et les illustrations de l''application.', 'startup', false, 30, 1),
  ('application-a-z', 'Design & Expérience', 'Designer de marque', 'Définit l''identité : logo, ton, couleurs, et veille à leur usage partout.', 'startup', false, 31, 1),
  ('application-a-z', 'Design & Expérience', 'Motion designer', 'Réalise les animations et vidéos courtes qui expliquent l''application.', 'scaleup', false, 32, 1),
  ('application-a-z', 'Design & Expérience', 'Designer accessibilité', 'Vérifie contrastes, tailles, ordre de lecture et alternatives textuelles sur chaque écran.', 'scaleup', false, 33, 1),
  ('application-a-z', 'Design & Expérience', 'Designer de données', 'Rend lisibles les tableaux de bord et graphiques de l''application.', 'scaleup', false, 34, 1),
  ('application-a-z', 'Design & Expérience', 'Designer des parcours d''accueil', 'Conçoit les premières minutes : inscription, présentation, premier succès de l''utilisateur.', 'startup', false, 35, 1),
  ('application-a-z', 'Design & Expérience', 'Designer des notifications', 'Décide quand, comment et avec quels mots l''application sollicite l''utilisateur, sans le harceler.', 'scaleup', false, 36, 1),
  ('application-a-z', 'Design & Expérience', 'Prototypiste', 'Fabrique des prototypes cliquables rapides pour tester une idée avant de la coder.', 'startup', false, 37, 1),
  ('application-a-z', 'Design & Expérience', 'Designer d''illustrations', 'Dessine les illustrations des écrans vides, d''erreur et d''accueil.', 'scaleup', false, 38, 1),
  ('application-a-z', 'Design & Expérience', 'Responsable des tests d''utilisabilité', 'Organise des sessions de tests réguliers et tient le registre des problèmes trouvés.', 'scaleup', false, 39, 1),
  ('application-a-z', 'Design & Expérience', 'Coordinateur ou coordinatrice design', 'Planifie les revues de design et fait le lien avec le produit et le développement.', 'megacorp', false, 40, 1),
  ('application-a-z', 'Front-end & Mobile', 'Responsable du front-end', 'Choisit l''architecture de l''interface et garantit sa qualité, sa vitesse et sa lisibilité.', 'startup', true, 41, 1),
  ('application-a-z', 'Front-end & Mobile', 'Développeur ou développeuse front-end', 'Code les écrans web à partir des maquettes, proprement et testés.', 'cocon', false, 42, 4),
  ('application-a-z', 'Front-end & Mobile', 'Développeur ou développeuse mobile iOS', 'Construit et publie l''application iPhone, en respectant les règles d''Apple.', 'startup', false, 43, 2),
  ('application-a-z', 'Front-end & Mobile', 'Développeur ou développeuse mobile Android', 'Construit et publie l''application Android, testée sur des téléphones d''entrée de gamme.', 'startup', false, 44, 2),
  ('application-a-z', 'Front-end & Mobile', 'Développeur ou développeuse multiplateforme', 'Partage le code entre web, iOS et Android sans sacrifier l''expérience.', 'cocon', false, 45, 2),
  ('application-a-z', 'Front-end & Mobile', 'Intégrateur ou intégratrice web', 'Transforme les maquettes en pages fidèles au pixel, sur tous les navigateurs.', 'startup', false, 46, 1),
  ('application-a-z', 'Front-end & Mobile', 'Spécialiste de la performance front', 'Réduit le temps de chargement et le poids des pages, surtout sur réseau lent.', 'scaleup', false, 47, 1),
  ('application-a-z', 'Front-end & Mobile', 'Spécialiste accessibilité front', 'Rend chaque composant utilisable au clavier et au lecteur d''écran.', 'scaleup', false, 48, 1),
  ('application-a-z', 'Front-end & Mobile', 'Développeur ou développeuse des composants', 'Construit la bibliothèque de composants partagés du système de design.', 'scaleup', false, 49, 1),
  ('application-a-z', 'Front-end & Mobile', 'Spécialiste des applications web progressives', 'Rend l''application installable et utilisable hors ligne.', 'startup', false, 50, 1),
  ('application-a-z', 'Front-end & Mobile', 'Spécialiste de l''internationalisation front', 'Gère les traductions, formats de dates, monnaies et écritures de droite à gauche.', 'scaleup', false, 51, 1),
  ('application-a-z', 'Front-end & Mobile', 'Développeur ou développeuse des notifications', 'Branche les notifications push et en application, avec les préférences de l''utilisateur.', 'startup', false, 52, 1),
  ('application-a-z', 'Front-end & Mobile', 'Spécialiste de l''état et des données front', 'Organise le cache, la synchronisation et le hors-ligne côté interface.', 'scaleup', false, 53, 1),
  ('application-a-z', 'Front-end & Mobile', 'Testeur ou testeuse front automatisé', 'Écrit les tests de bout en bout qui cliquent dans l''application comme un utilisateur.', 'startup', false, 54, 1),
  ('application-a-z', 'Front-end & Mobile', 'Spécialiste de la publication sur les stores', 'Prépare les fiches, captures et versions pour l''App Store et Google Play.', 'startup', false, 55, 1),
  ('application-a-z', 'Front-end & Mobile', 'Développeur ou développeuse des animations', 'Code les transitions et animations sans ralentir l''application.', 'scaleup', false, 56, 1),
  ('application-a-z', 'Front-end & Mobile', 'Spécialiste de la sécurité front', 'Protège l''interface contre les injections, les fuites de jetons et les failles courantes.', 'scaleup', false, 57, 1),
  ('application-a-z', 'Front-end & Mobile', 'Développeur ou développeuse des tableaux de bord', 'Construit les écrans de statistiques et d''administration.', 'startup', false, 58, 1),
  ('application-a-z', 'Front-end & Mobile', 'Spécialiste de la compatibilité appareils', 'Teste sur une variété de téléphones, tailles d''écran et versions de système.', 'scaleup', false, 59, 1),
  ('application-a-z', 'Front-end & Mobile', 'Coordinateur ou coordinatrice des versions mobiles', 'Planifie les versions, les tests bêta et les déploiements progressifs sur les stores.', 'scaleup', false, 60, 1),
  ('application-a-z', 'Back-end & API', 'Responsable du back-end', 'Choisit l''architecture serveur et garantit sa fiabilité, sa sécurité et sa simplicité.', 'startup', true, 61, 1),
  ('application-a-z', 'Back-end & API', 'Développeur ou développeuse back-end', 'Écrit les services, la logique métier et les API qui font tourner l''application.', 'cocon', false, 62, 4),
  ('application-a-z', 'Back-end & API', 'Architecte logiciel', 'Dessine le découpage en services et les décisions techniques qui tiendront dans le temps.', 'scaleup', false, 63, 1),
  ('application-a-z', 'Back-end & API', 'Développeur ou développeuse API', 'Conçoit des API claires, versionnées et documentées pour l''interface et les partenaires.', 'startup', false, 64, 2),
  ('application-a-z', 'Back-end & API', 'Spécialiste de l''authentification', 'Gère comptes, connexions, mots de passe, connexion unique et double authentification.', 'cocon', false, 65, 1),
  ('application-a-z', 'Back-end & API', 'Spécialiste des intégrations', 'Branche les services externes : e-mail, SMS, cartes, stockage, outils des clients.', 'startup', false, 66, 1),
  ('application-a-z', 'Back-end & API', 'Spécialiste des tâches de fond', 'Construit les files d''attente, tâches planifiées et traitements longs.', 'startup', false, 67, 1),
  ('application-a-z', 'Back-end & API', 'Spécialiste des notifications serveur', 'Envoie e-mails, SMS et notifications push au bon moment, sans doublon.', 'startup', false, 68, 1),
  ('application-a-z', 'Back-end & API', 'Spécialiste de la recherche', 'Construit la recherche de l''application : pertinence, filtres, tolérance aux fautes.', 'scaleup', false, 69, 1),
  ('application-a-z', 'Back-end & API', 'Spécialiste des fichiers et médias', 'Gère l''envoi, le redimensionnement et le stockage des photos, vidéos et documents.', 'startup', false, 70, 1),
  ('application-a-z', 'Back-end & API', 'Spécialiste du temps réel', 'Construit les messages instantanés, présences et mises à jour en direct.', 'scaleup', false, 71, 1),
  ('application-a-z', 'Back-end & API', 'Spécialiste de l''intelligence artificielle', 'Intègre les modèles d''IA utiles au produit, en maîtrisant leur coût et leurs erreurs.', 'startup', false, 72, 1),
  ('application-a-z', 'Back-end & API', 'Spécialiste de la performance serveur', 'Traque les lenteurs, met en cache et tient les temps de réponse sous contrôle.', 'scaleup', false, 73, 1),
  ('application-a-z', 'Back-end & API', 'Spécialiste de la sécurité applicative', 'Revoit le code et les accès pour fermer les failles avant qu''on les exploite.', 'startup', false, 74, 1),
  ('application-a-z', 'Back-end & API', 'Développeur ou développeuse des outils internes', 'Construit l''administration et les outils dont l''équipe a besoin chaque jour.', 'startup', false, 75, 1),
  ('application-a-z', 'Back-end & API', 'Spécialiste de la documentation technique', 'Tient à jour la documentation des API et des services, avec des exemples qui marchent.', 'scaleup', false, 76, 1),
  ('application-a-z', 'Back-end & API', 'Testeur ou testeuse back-end automatisé', 'Écrit les tests unitaires et d''intégration qui protègent la logique métier.', 'startup', false, 77, 1),
  ('application-a-z', 'Back-end & API', 'Spécialiste des webhooks et événements', 'Gère les événements échangés avec les partenaires, rejoués sans perte ni doublon.', 'scaleup', false, 78, 1),
  ('application-a-z', 'Back-end & API', 'Spécialiste des migrations', 'Fait évoluer le schéma et les données sans interruption ni perte.', 'scaleup', false, 79, 1),
  ('application-a-z', 'Back-end & API', 'Coordinateur ou coordinatrice technique', 'Suit la dette technique, les revues de code et les chantiers transverses.', 'megacorp', false, 80, 1),
  ('application-a-z', 'Données & Base de données', 'Responsable des données', 'Garantit que les données sont justes, protégées et utiles aux décisions.', 'startup', true, 81, 1),
  ('application-a-z', 'Données & Base de données', 'Administrateur ou administratrice de base de données', 'Veille à la santé, aux sauvegardes et à la performance de la base.', 'cocon', false, 82, 1),
  ('application-a-z', 'Données & Base de données', 'Concepteur ou conceptrice de schéma', 'Dessine les tables, relations et contraintes qui empêchent les données fausses.', 'cocon', false, 83, 1),
  ('application-a-z', 'Données & Base de données', 'Ingénieur ou ingénieure data', 'Construit les flux qui rassemblent et nettoient les données pour l''analyse.', 'startup', false, 84, 2),
  ('application-a-z', 'Données & Base de données', 'Analyste de données', 'Répond aux questions de l''équipe avec des chiffres vérifiés et leur période.', 'startup', false, 85, 2),
  ('application-a-z', 'Données & Base de données', 'Data scientist', 'Construit des modèles de prédiction ou de recommandation, et prouve qu''ils aident.', 'scaleup', false, 86, 1),
  ('application-a-z', 'Données & Base de données', 'Spécialiste de la qualité des données', 'Détecte doublons, trous et incohérences, et les fait corriger à la source.', 'scaleup', false, 87, 1),
  ('application-a-z', 'Données & Base de données', 'Spécialiste des règles d''accès', 'Écrit les règles qui disent qui voit quoi, ligne par ligne, et les teste.', 'startup', false, 88, 1),
  ('application-a-z', 'Données & Base de données', 'Spécialiste des sauvegardes et reprises', 'Teste réellement la restauration des données, pas seulement leur sauvegarde.', 'startup', false, 89, 1),
  ('application-a-z', 'Données & Base de données', 'Analyste produit', 'Mesure l''usage des fonctionnalités et dit ce qui marche et ce qui ne marche pas.', 'startup', false, 90, 1),
  ('application-a-z', 'Données & Base de données', 'Spécialiste des tableaux de bord', 'Construit les tableaux de bord que l''équipe consulte vraiment.', 'startup', false, 91, 1),
  ('application-a-z', 'Données & Base de données', 'Spécialiste de la gouvernance des données', 'Tient le registre des données, leur durée de conservation et leurs responsables.', 'scaleup', false, 92, 1),
  ('application-a-z', 'Données & Base de données', 'Spécialiste de la protection des données', 'Anonymise, chiffre et limite les données personnelles au strict nécessaire.', 'startup', false, 93, 1),
  ('application-a-z', 'Données & Base de données', 'Ingénieur ou ingénieure analytique', 'Transforme les données brutes en tables propres et documentées pour l''analyse.', 'scaleup', false, 94, 1),
  ('application-a-z', 'Données & Base de données', 'Spécialiste de la mesure d''audience', 'Pose les événements de suivi correctement et respecte le consentement.', 'startup', false, 95, 1),
  ('application-a-z', 'Données & Base de données', 'Spécialiste des données de test', 'Prépare des jeux de données réalistes et séparés des vraies données.', 'scaleup', false, 96, 1),
  ('application-a-z', 'Données & Base de données', 'Spécialiste des exports et imports', 'Permet d''entrer et de sortir les données (CSV, Excel, API) sans perte.', 'startup', false, 97, 1),
  ('application-a-z', 'Données & Base de données', 'Spécialiste de la recherche vectorielle', 'Indexe documents et contenus pour la recherche par le sens et l''IA.', 'scaleup', false, 98, 1),
  ('application-a-z', 'Données & Base de données', 'Spécialiste de la performance des requêtes', 'Optimise les requêtes lentes et les index sans casser les résultats.', 'scaleup', false, 99, 1),
  ('application-a-z', 'Données & Base de données', 'Coordinateur ou coordinatrice data', 'Priorise les demandes de chiffres et évite les définitions contradictoires.', 'megacorp', false, 100, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Responsable des paiements', 'Garantit que chaque paiement passe, est juste, et se retrouve en comptabilité.', 'startup', true, 101, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Intégrateur ou intégratrice de paiement', 'Branche les moyens de paiement (carte, mobile money, virement) de façon sûre.', 'cocon', false, 102, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste des abonnements', 'Gère essais, renouvellements, changements de formule et résiliations.', 'startup', false, 103, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste de la facturation', 'Émet des factures justes, dans la bonne monnaie et conformes au pays.', 'startup', false, 104, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste du rapprochement', 'Vérifie que ce qui est encaissé correspond à ce qui est vendu, au centime près.', 'startup', false, 105, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste de la fraude', 'Repère les paiements suspects et les comptes frauduleux sans bloquer les honnêtes.', 'scaleup', false, 106, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste des remboursements et litiges', 'Traite remboursements et contestations de paiement dans les délais.', 'startup', false, 107, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste des taxes', 'Applique la bonne TVA ou taxe selon le pays et le produit.', 'scaleup', false, 108, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste des achats intégrés', 'Gère les achats dans l''App Store et Google Play et leurs règles.', 'startup', false, 109, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste des multidevises', 'Affiche les prix dans la monnaie de l''utilisateur et gère le change proprement.', 'scaleup', false, 110, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste des versements aux vendeurs', 'Paie les vendeurs ou créateurs d''une place de marché, à temps et sans erreur.', 'scaleup', false, 111, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Analyste des revenus', 'Suit chiffre d''affaires, revenu récurrent, désabonnements et valeur d''un client.', 'startup', false, 112, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste de la conformité paiement', 'Veille aux normes de sécurité des cartes et aux règles des prestataires.', 'scaleup', false, 113, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste des moyens de paiement locaux', 'Ajoute les moyens de paiement propres à chaque marché visé.', 'scaleup', false, 114, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste de la page de paiement', 'Rend la page de paiement rapide, claire et rassurante pour moins d''abandons.', 'startup', false, 115, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste des coupons et promotions', 'Crée codes promo et offres sans ouvrir de failles.', 'scaleup', false, 116, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste de la trésorerie', 'Prévoit les entrées et sorties d''argent liées aux paiements.', 'scaleup', false, 117, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste des relances de paiement', 'Relance les paiements échoués avant de perdre le client.', 'scaleup', false, 118, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Spécialiste du portefeuille et des crédits', 'Gère soldes, crédits et bons d''achat dans l''application.', 'megacorp', false, 119, 1),
  ('application-a-z', 'Paiements & Monétisation', 'Coordinateur ou coordinatrice finance produit', 'Fait le lien entre paiements, comptabilité et produit.', 'megacorp', false, 120, 1),
  ('application-a-z', 'Croissance & Marketing', 'Responsable de la croissance', 'Fait venir et revenir les utilisateurs, avec des expériences mesurées.', 'startup', true, 121, 1),
  ('application-a-z', 'Croissance & Marketing', 'Responsable marketing', 'Porte le message de l''application et choisit les canaux où parler.', 'cocon', false, 122, 1),
  ('application-a-z', 'Croissance & Marketing', 'Spécialiste de l''acquisition payante', 'Achète de la publicité rentable et coupe ce qui ne rapporte pas.', 'startup', false, 123, 1),
  ('application-a-z', 'Croissance & Marketing', 'Spécialiste du référencement', 'Fait trouver l''application sur les moteurs de recherche et les stores.', 'startup', false, 124, 1),
  ('application-a-z', 'Croissance & Marketing', 'Spécialiste de l''optimisation des stores', 'Améliore la fiche de l''app dans les stores pour plus de téléchargements.', 'startup', false, 125, 1),
  ('application-a-z', 'Croissance & Marketing', 'Responsable des contenus', 'Écrit articles, guides et publications qui attirent et aident les utilisateurs.', 'startup', false, 126, 1),
  ('application-a-z', 'Croissance & Marketing', 'Community manager', 'Anime les réseaux sociaux et répond à la communauté avec le ton de la marque.', 'cocon', false, 127, 1),
  ('application-a-z', 'Croissance & Marketing', 'Spécialiste de l''e-mail et du CRM', 'Envoie les bons messages au bon moment selon le parcours de chaque utilisateur.', 'startup', false, 128, 1),
  ('application-a-z', 'Croissance & Marketing', 'Spécialiste de l''activation', 'Aide les nouveaux inscrits à réussir leur première action.', 'startup', false, 129, 1),
  ('application-a-z', 'Croissance & Marketing', 'Spécialiste de la rétention', 'Comprend pourquoi les gens partent et les fait revenir.', 'scaleup', false, 130, 1),
  ('application-a-z', 'Croissance & Marketing', 'Spécialiste du parrainage', 'Construit les programmes où les utilisateurs invitent leurs proches.', 'scaleup', false, 131, 1),
  ('application-a-z', 'Croissance & Marketing', 'Spécialiste des partenariats et influence', 'Trouve et suit les partenaires et créateurs qui recommandent l''app.', 'scaleup', false, 132, 1),
  ('application-a-z', 'Croissance & Marketing', 'Spécialiste des relations presse', 'Obtient des articles et gère la réputation de l''application.', 'scaleup', false, 133, 1),
  ('application-a-z', 'Croissance & Marketing', 'Spécialiste des événements', 'Organise lancements, démonstrations et participations à des salons.', 'scaleup', false, 134, 1),
  ('application-a-z', 'Croissance & Marketing', 'Spécialiste de la marque employeur', 'Fait connaître l''équipe pour attirer les bons talents.', 'megacorp', false, 135, 1),
  ('application-a-z', 'Croissance & Marketing', 'Analyste marketing', 'Mesure le coût et le rendement de chaque canal, sans double compte.', 'startup', false, 136, 1),
  ('application-a-z', 'Croissance & Marketing', 'Vidéaste', 'Réalise les vidéos de démonstration et les formats courts pour les réseaux.', 'scaleup', false, 137, 1),
  ('application-a-z', 'Croissance & Marketing', 'Commercial ou commerciale', 'Vend l''application aux entreprises clientes quand le modèle le demande.', 'startup', false, 138, 2),
  ('application-a-z', 'Croissance & Marketing', 'Responsable de la localisation marketing', 'Adapte campagnes et messages à chaque pays et chaque langue.', 'scaleup', false, 139, 1),
  ('application-a-z', 'Croissance & Marketing', 'Coordinateur ou coordinatrice marketing', 'Tient le calendrier des campagnes et publications.', 'scaleup', false, 140, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Responsable juridique', 'Protège l''application et l''entreprise : contrats, conformité, propriété intellectuelle.', 'startup', true, 141, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Juriste contrats', 'Rédige et relit contrats clients, fournisseurs et partenaires.', 'startup', false, 142, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Délégué ou déléguée à la protection des données', 'Veille au respect des lois sur les données personnelles dans chaque pays visé.', 'startup', false, 143, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Rédacteur ou rédactrice des conditions d''utilisation', 'Écrit des conditions et une politique de confidentialité claires et à jour.', 'cocon', false, 144, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Responsable de la sécurité des systèmes', 'Définit la politique de sécurité et vérifie qu''elle est appliquée.', 'startup', false, 145, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste des tests d''intrusion', 'Attaque l''application comme un pirate pour trouver les failles avant eux.', 'scaleup', false, 146, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste de la conformité des stores', 'Vérifie que l''app respecte les règles d''Apple et Google avant chaque version.', 'startup', false, 147, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste de la propriété intellectuelle', 'Protège marque, logo et contenus, et vérifie les licences utilisées.', 'scaleup', false, 148, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste des licences logicielles', 'Vérifie que chaque bibliothèque utilisée a une licence compatible.', 'startup', false, 149, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste de la modération', 'Définit et applique les règles de contenu pour une communauté saine.', 'startup', false, 150, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste de la conformité financière', 'Vérifie les obligations liées aux paiements et à la lutte contre la fraude.', 'scaleup', false, 151, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste de l''accessibilité légale', 'Suit les obligations d''accessibilité numérique selon les pays.', 'scaleup', false, 152, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste de la gestion des incidents de sécurité', 'Organise la réponse à une fuite ou une attaque, et la déclaration si la loi l''exige.', 'scaleup', false, 153, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste de la gestion des accès', 'Donne et retire les droits de l''équipe au juste nécessaire.', 'startup', false, 154, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste de la conformité IA', 'Veille aux règles sur l''IA : transparence, données d''entraînement, usages interdits.', 'scaleup', false, 155, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste des cookies et du consentement', 'Gère les bandeaux de consentement et le respect des choix des utilisateurs.', 'startup', false, 156, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste des demandes des autorités', 'Traite les demandes officielles d''accès aux données, dans le respect de la loi.', 'megacorp', false, 157, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Spécialiste de la conformité des mineurs', 'Protège les utilisateurs mineurs selon les lois de chaque pays.', 'scaleup', false, 158, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Auditeur ou auditrice interne', 'Vérifie régulièrement que les règles internes sont suivies.', 'megacorp', false, 159, 1),
  ('application-a-z', 'Juridique, Conformité & Sécurité', 'Coordinateur ou coordinatrice conformité', 'Tient le registre des obligations et leur calendrier.', 'megacorp', false, 160, 1),
  ('application-a-z', 'Support & Communauté', 'Responsable du support', 'Garantit des réponses rapides, justes et aimables à chaque utilisateur.', 'startup', true, 161, 1),
  ('application-a-z', 'Support & Communauté', 'Agent de support niveau 1', 'Répond aux questions courantes et résout les problèmes simples.', 'cocon', false, 162, 4),
  ('application-a-z', 'Support & Communauté', 'Agent de support niveau 2', 'Traite les cas complexes transmis par le niveau 1, avec l''aide technique.', 'startup', false, 163, 2),
  ('application-a-z', 'Support & Communauté', 'Spécialiste de la base de connaissances', 'Écrit les articles d''aide qui répondent avant qu''on pose la question.', 'startup', false, 164, 1),
  ('application-a-z', 'Support & Communauté', 'Spécialiste des retours utilisateurs', 'Classe les retours et les transmet au produit avec leur fréquence.', 'startup', false, 165, 1),
  ('application-a-z', 'Support & Communauté', 'Responsable de la communauté', 'Anime forums et groupes d''utilisateurs, et fait remonter leurs idées.', 'startup', false, 166, 1),
  ('application-a-z', 'Support & Communauté', 'Spécialiste de l''accueil des clients', 'Accompagne les nouveaux clients importants dans leurs premières semaines.', 'scaleup', false, 167, 1),
  ('application-a-z', 'Support & Communauté', 'Chargé ou chargée de la réussite client', 'Aide les clients à obtenir des résultats et prévient les départs.', 'scaleup', false, 168, 2),
  ('application-a-z', 'Support & Communauté', 'Spécialiste du support technique', 'Diagnostique les bugs signalés et les transmet à l''équipe avec les étapes pour les reproduire.', 'startup', false, 169, 1),
  ('application-a-z', 'Support & Communauté', 'Spécialiste du support multilingue', 'Répond aux utilisateurs dans leur langue.', 'scaleup', false, 170, 1),
  ('application-a-z', 'Support & Communauté', 'Spécialiste des avis sur les stores', 'Répond aux avis sur l''App Store et Google Play, avec tact.', 'startup', false, 171, 1),
  ('application-a-z', 'Support & Communauté', 'Spécialiste de la qualité du support', 'Relit les réponses, mesure la satisfaction et forme l''équipe.', 'scaleup', false, 172, 1),
  ('application-a-z', 'Support & Communauté', 'Spécialiste des outils de support', 'Configure la messagerie, les modèles de réponse et le tri des demandes.', 'scaleup', false, 173, 1),
  ('application-a-z', 'Support & Communauté', 'Spécialiste de la formation des utilisateurs', 'Crée tutoriels, webinaires et guides de prise en main.', 'scaleup', false, 174, 1),
  ('application-a-z', 'Support & Communauté', 'Spécialiste des remontées d''incidents', 'Prévient les utilisateurs quand un service est en panne, et quand il revient.', 'scaleup', false, 175, 1),
  ('application-a-z', 'Support & Communauté', 'Modérateur ou modératrice', 'Applique les règles de la communauté et retire les contenus interdits.', 'startup', false, 176, 1),
  ('application-a-z', 'Support & Communauté', 'Ambassadeur ou ambassadrice bêta', 'Anime les testeurs de nouvelles versions et recueille leurs retours.', 'scaleup', false, 177, 1),
  ('application-a-z', 'Support & Communauté', 'Spécialiste des réclamations', 'Traite plaintes et litiges avec les utilisateurs, jusqu''à la solution.', 'scaleup', false, 178, 1),
  ('application-a-z', 'Support & Communauté', 'Analyste du support', 'Mesure les volumes, délais et motifs de contact pour réduire les demandes.', 'scaleup', false, 179, 1),
  ('application-a-z', 'Support & Communauté', 'Coordinateur ou coordinatrice du support', 'Organise les plannings et la couverture horaire.', 'megacorp', false, 180, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Responsable de l''infrastructure', 'Garantit que l''application tourne, tient la charge et coûte ce qu''elle doit.', 'startup', true, 181, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Ingénieur ou ingénieure DevOps', 'Automatise la construction, les tests et le déploiement du code.', 'cocon', false, 182, 2),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Ingénieur ou ingénieure fiabilité', 'Surveille la disponibilité, fixe des objectifs de service et réduit les pannes.', 'scaleup', false, 183, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Administrateur ou administratrice cloud', 'Gère serveurs, réseaux, domaines et certificats chez l''hébergeur.', 'startup', false, 184, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Spécialiste de l''intégration continue', 'Fait tourner les tests à chaque modification et bloque ce qui casse.', 'startup', false, 185, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Spécialiste du déploiement', 'Met en ligne les nouvelles versions sans coupure, avec retour arrière possible.', 'startup', false, 186, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Spécialiste de la supervision', 'Pose alertes et tableaux de bord qui préviennent avant les utilisateurs.', 'startup', false, 187, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Spécialiste des coûts d''infrastructure', 'Suit la facture d''hébergement et d''IA, et la réduit sans risque.', 'scaleup', false, 188, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Responsable qualité', 'Définit comment on teste et ce qui doit être vrai avant chaque mise en ligne.', 'startup', false, 189, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Testeur ou testeuse manuel', 'Joue les parcours à la main comme un utilisateur, sur de vrais appareils.', 'cocon', false, 190, 2),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Ingénieur ou ingénieure en automatisation des tests', 'Automatise les tests de régression pour aller vite sans casser.', 'startup', false, 191, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Spécialiste des tests de charge', 'Vérifie que l''application tient quand beaucoup d''utilisateurs arrivent en même temps.', 'scaleup', false, 192, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Spécialiste de la reprise après sinistre', 'Prépare et teste le plan pour repartir après une panne majeure.', 'scaleup', false, 193, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Spécialiste des environnements', 'Tient les environnements de test et de préproduction fidèles à la production.', 'startup', false, 194, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Spécialiste de la sécurité de l''infrastructure', 'Protège serveurs, secrets et accès techniques.', 'scaleup', false, 195, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Spécialiste des réseaux de diffusion', 'Rapproche les contenus des utilisateurs, partout dans le monde.', 'scaleup', false, 196, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Gestionnaire des versions', 'Planifie les versions, rédige les notes de version et coordonne les équipes.', 'startup', false, 197, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Spécialiste de l''observabilité', 'Rassemble journaux, traces et métriques pour trouver vite la cause d''un bug.', 'scaleup', false, 198, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Astreinte et gestion des incidents', 'Répond aux pannes jour et nuit, rétablit le service et écrit le retour d''expérience.', 'scaleup', false, 199, 1),
  ('application-a-z', 'Infrastructure, Qualité & Déploiement', 'Coordinateur ou coordinatrice des opérations', 'Tient le registre des incidents, des changements et des maintenances.', 'megacorp', false, 200, 1)
) as v(modele, departement, poste, mandat, des_la_taille, est_directeur, ordre, poids)
where not exists (select 1 from public.studio_modele_postes p where p.modele = 'application-a-z');

-- Les deux postes manquants.
insert into public.studio_modele_postes (modele, departement, poste, mandat, des_la_taille, est_directeur, ordre, poids)
select 'promoteur-et-agence-immobiliere', 'Finance & Juridique', 'Asset manager immobilier',
  'Pilote la valeur du patrimoine : rendement locatif, vacance, travaux, et arbitrages d''achat ou de vente, immeuble par immeuble.',
  'scaleup', false, 48, 1
where not exists (select 1 from public.studio_modele_postes where modele = 'promoteur-et-agence-immobiliere' and poste = 'Asset manager immobilier');

insert into public.studio_modele_postes (modele, departement, poste, mandat, des_la_taille, est_directeur, ordre, poids)
select 'produit', 'Direction', 'Responsable de l''innovation',
  'Repère les usages et technologies qui peuvent changer le produit, les teste en petit avec un critère de réussite, et arrête vite ce qui échoue.',
  'scaleup', false, 1796, 1
where not exists (select 1 from public.studio_modele_postes where modele = 'produit' and poste = 'Responsable de l''innovation');
